import { Industry, NavLinkData, Testimonial, Product, Category } from './types';

export const NAV_LINKS: NavLinkData[] = [
    { name: 'Home', path: '/' },
    { name: 'About Us', path: '/about' },
    { name: 'Industries', path: '/industries' },
    { name: 'Products', path: '/products' },
    { name: 'Blog', path: '/blog' },
    { name: 'Contact', path: '/contact' },
    { name: 'Request a Quote', path: '/request-quote', isButton: true },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
    {
        quote: "Tape India's VHB tapes have revolutionized our assembly process. The bond is incredibly strong, and their technical support is top-notch.",
        author: "Ravi Sharma",
        company: "Lead Engineer, Auto Components Ltd."
    },
    {
        quote: "The quality and consistency of their packaging tapes have significantly reduced our shipping damages. A reliable partner for our logistics.",
        author: "Priya Menon",
        company: "Supply Chain Manager, E-commerce Giant"
    },
    {
        quote: "We rely on their high-temperature masking tapes for our powder coating line. They perform flawlessly and remove cleanly every time.",
        author: "Anil Kumar",
        company: "Production Head, Metal Fabricators Inc."
    }
];

export const INDUSTRIES: Industry[] = [
    { 
        id: 'packaging-industry', 
        name: 'Packaging', 
        subtitle: 'Sealing, bundling, and safety.',
        icon: 'BoxIcon',
        gradientClasses: 'from-amber-500 via-orange-600 to-red-700',
    },
    { 
        id: 'hvac-industry', 
        name: 'HVAC',
        subtitle: 'Duct sealing & thermal control.',
        icon: 'WindIcon',
        gradientClasses: 'from-cyan-500 via-cyan-600 to-blue-700',
    },
    { 
        id: 'print-labels-signage-industry', 
        name: 'Print & Signage',
        subtitle: 'Mounting, printing, and bonding.',
        icon: 'LayersIcon',
        gradientClasses: 'from-slate-500 via-slate-600 to-slate-700',
    },
    { 
        id: 'electronic-industry', 
        name: 'Electronics',
        subtitle: 'Shielding & high-temp solutions.',
        icon: 'CpuIcon',
        gradientClasses: 'from-blue-600 via-blue-700 to-indigo-800',
        highlight: true
    },
    { 
        id: 'reflective-safety-industry', 
        name: 'Reflective & Safety',
        subtitle: 'High-visibility tapes and fabrics.',
        icon: 'SunIcon',
        gradientClasses: 'from-yellow-400 via-yellow-500 to-orange-500',
    },
    { 
        id: 'ptfe-teflon-industry', 
        name: 'PTFE & Teflon',
        subtitle: 'High-temperature, non-stick.',
        icon: 'SparklesIcon',
        gradientClasses: 'from-green-500 via-green-600 to-teal-700',
    },
];

// This is the definitive source for all product CONTENT.
// It will be merged with SEO data from seoData.ts.
export const PRODUCTS: Omit<Product, 'seo'>[] = [
    // --- Safety Tapes ---
    { id: 'hazard-tape', name: 'Hazard Warning & Safety Stripe Tape', shortDescription: 'Durable PVC tape for marking physical hazards and safety zones in industrial environments.', category: 'safety-tapes', features: ['High-contrast colors (Black/Yellow, Red/White)', 'Strong PVC backing for durability', 'Aggressive rubber adhesive for strong bond', 'Resistant to abrasion, moisture, and wear'], uses: ['Marking physical hazards', 'Aisle marking in warehouses', 'Indicating safety equipment locations', 'Construction site warnings'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/hazard-tape.webp'] },
    { id: 'floor-marking-tape', name: 'Heavy-Duty Floor Marking Tape', shortDescription: 'High-quality vinyl tape for aisle marking, workflow organization, and safety warnings in factories.', category: 'safety-tapes', features: ['Tough vinyl backing resists heavy traffic', 'Available in multiple solid colors', 'Removes cleanly without residue', 'Easy to apply'], uses: ['Warehouse aisle marking', 'Designating work cells', 'Social distancing markers', 'Safety equipment zones'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/floor-marking-tape.webp'] },
    { id: 'anti-skid-tape', name: 'Heavy-Duty Anti-Skid & Anti-Slip Tape', shortDescription: 'Prevent slips and falls with our abrasive anti-slip tapes, perfect for stairs, ramps, and industrial floors.', category: 'safety-tapes', features: ['High-traction mineral-coated surface', 'Durable and long-lasting adhesive', 'Water and chemical resistant', 'Suitable for indoor and outdoor use'], uses: ['Stairs and steps', 'Ramps and walkways', 'Loading docks', 'Wet floor areas'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/anti-skid-tape.webp'] },
    { id: 'caution-tape', name: 'Non-Adhesive Caution & Warning Tape', shortDescription: 'High-visibility, non-adhesive tape for cordoning off restricted areas and communicating warnings.', category: 'safety-tapes', features: ['Bright, fade-resistant colors', 'Durable polyethylene construction', 'Weatherproof and tear-resistant', 'Lightweight and easy to use'], uses: ['Construction sites', 'Hazardous material spills', 'Crime scenes', 'Event crowd control'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/caution-tape.webp'] },
    { id: 'barricade-tape', name: 'Non-Adhesive Barricade Tape', shortDescription: 'Lightweight and economical tape for marking boundaries and restricted areas.', category: 'safety-tapes', features: ['High visibility', 'Tear-resistant polyethylene', 'Non-adhesive for easy removal'], uses: ['Crowd control', 'Construction sites', 'Law enforcement'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/caution-tape.webp'] },
    { id: 'tamper-proof-security-packing-tape', name: 'Tamper-Proof Security Packing Tape', shortDescription: 'High-security packaging tape that reveals a "VOID" message when removed.', category: 'safety-tapes', features: ['Provides visual evidence of tampering', 'Strong polyester backing', 'Aggressive adhesive for secure sealing'], uses: ['Sealing high-value goods', 'Pharmaceutical packaging', 'Electronics shipping'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/tamper-proof-tape.webp'] },
    { id: 'nastro-heavy-duty-floor-marking-tape', name: 'Nastro Heavy Duty Floor Marking Tape', shortDescription: 'Premium grade, extra-thick floor marking tape for high-traffic industrial areas.', category: 'safety-tapes', features: ['Laminated for extreme durability', 'Resists forklifts and heavy machinery', 'Beveled edges to prevent lifting'], uses: ['Heavy industrial warehouses', 'Manufacturing facilities', 'Logistics centers'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/nastro-tape.webp'] },
    { id: 'glow-in-the-dark-tape', name: 'Glow in the Dark Tape', shortDescription: 'Photoluminescent tape that glows in the dark after being charged by light, for emergency exit marking.', category: 'safety-tapes', features: ['High-intensity glow', 'Charges quickly from any light source', 'Durable vinyl construction'], uses: ['Marking escape routes', 'Stairways and handrails', 'Light switch surrounds'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/glow-tape.webp'] },
    { id: 'photoluminescent-film', name: 'Photoluminescent Film', shortDescription: 'High-grade photoluminescent vinyl film for creating safety signs and markings.', category: 'safety-tapes', features: ['Long-lasting glow properties', 'Available in adhesive and rigid forms', 'Meets safety regulations'], uses: ['Exit signs', 'Fire safety signage', 'Marine safety applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/photoluminescent-film.webp'] },
    { id: 'anti-skid-tape-with-centre-glow', name: 'Anti-Skid Tape with Centre Glow', shortDescription: 'Combines high-traction anti-slip surface with a central photoluminescent strip for visibility in darkness.', category: 'safety-tapes', features: ['Dual-purpose safety', 'Mineral-coated anti-slip surface', 'Bright glow-in-the-dark center line'], uses: ['Emergency exit stairs', 'Dark corridors and walkways', 'Industrial platforms'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/anti-skid-glow.webp'] },
    { id: 'esd-floor-marking-tape', name: 'ESD Floor Marking Tape', shortDescription: 'Specifically designed for marking floors in Electrostatic Protected Areas (EPAs).', category: 'safety-tapes', features: ['Low static-generating properties', 'Clear ESD symbol printed', 'Durable for foot traffic'], uses: ['Defining EPA boundaries', 'Marking walkways in electronics labs', 'Cleanroom applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/esd-floor-tape.webp'] },
    { id: 'glow-in-dark-marking-tapes', name: 'Glow in Dark Marking Tapes', shortDescription: 'Versatile photoluminescent tapes for various safety and decorative marking applications.', category: 'safety-tapes', features: ['Available in various widths', 'Easy to apply', 'Long-lasting afterglow'], uses: ['Directional marking', 'Stage and theater marking', 'Home safety'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/glow-tape.webp'] },
    { id: 'heavy-duty-anti-skid-tape', name: 'Heavy Duty Anti-Skid Tape', shortDescription: 'Our toughest anti-slip tape with large grit particles for extreme industrial and outdoor environments.', category: 'safety-tapes', features: ['Extra-coarse abrasive surface', 'Resists oil, water, and heavy wear', 'Aggressive adhesive for rough surfaces'], uses: ['Offshore oil rigs', 'Manufacturing plants', 'Construction vehicles'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/anti-skid-tape.webp'] },
    { id: 'anti-slip-tape-for-bath-and-shower', name: 'Anti-Slip Tape for Bath and Shower', shortDescription: 'Provides a safe, non-abrasive, comfortable grip in wet areas like bathrooms and showers.', category: 'safety-tapes', features: ['Waterproof and mold-resistant', 'Soft-textured, non-abrasive surface', 'Clear design blends with decor'], uses: ['Bathtubs and shower floors', 'Around swimming pools', 'Locker rooms'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/bath-anti-slip.webp'] },

    // --- Reflective Tapes ---
    { id: 'silver-tc-reflective-tape', name: 'Silver TC Sew-On Reflective Tape', shortDescription: 'High-quality silver TC tape for sewing onto safety vests and workwear to enhance visibility.', category: 'reflective-tapes', features: ['High reflectivity (EN 20471 compliant)', 'Durable TC (Terylene/Cotton) backing', 'Washable and long-lasting', 'Easy to sew'], uses: ['Safety vests', 'Work jackets and pants', 'Firefighter uniforms', 'Jogging and cycling gear'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/silver-reflective-tape.webp'] },
    { id: 'heat-transfer-reflective-tape', name: 'Heat Transfer Reflective Film', shortDescription: 'Iron-on reflective material for safety garments, providing high visibility after application.', category: 'reflective-tapes', features: ['Applies with heat press or iron', 'Excellent reflectivity', 'Durable through washing'], uses: ['T-shirts and sportswear', 'Work uniforms', 'Caps and bags'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/heat-transfer-tape.webp'] },
    { id: 'vinyl-heat-transfer-reflective-film', name: 'Vinyl Heat Transfer Reflective Film', shortDescription: 'Flexible, plotter-cuttable reflective vinyl for custom designs on textiles.', category: 'reflective-tapes', features: ['Stretchable and flexible', 'Easy to weed and apply', 'Bright reflective finish'], uses: ['Custom logos on sportswear', 'Athletic apparel', 'Fashion garments'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/vinyl-heat-transfer.webp'] },
    { id: 'pvc-reflective-tape', name: 'PVC Reflective Tape', shortDescription: 'Durable and weatherproof PVC reflective tape with an aggressive adhesive for vehicles and outdoor signage.', category: 'reflective-tapes', features: ['Microprismatic technology for high brightness', 'Weather and solvent resistant', 'Strong adhesive backing'], uses: ['Trucks and trailers', 'Roadside signs', 'Bollards and barriers'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/pvc-reflective.webp'] },
    { id: 'reflective-yarn-thread', name: 'Reflective Yarn & Thread', shortDescription: 'Reflective thread for weaving, knitting, or embroidering into textiles for integrated visibility.', category: 'reflective-tapes', features: ['Can be woven or sewn', 'Provides 360-degree reflectivity', 'Soft and flexible'], uses: ['Sportswear', 'Shoelaces', 'Hats and gloves'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/reflective-thread.webp'] },
    { id: 'flame-retardant-reflective-tape', name: 'Flame Retardant Reflective Tape', shortDescription: 'Specialized reflective tape designed for firefighter uniforms and industrial workwear in high-heat environments.', category: 'reflective-tapes', features: ['Meets flame retardant standards (e.g., NFPA)', 'Aramid fiber backing', 'High heat resistance'], uses: ['Firefighter turnout gear', 'Welding apparel', 'Oil and gas industry workwear'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/fr-reflective-tape.webp'] },
    { id: 'hi-reflective-polyester-fabric', name: 'Hi-Reflective Polyester Fabric', shortDescription: 'High-visibility polyester fabric for manufacturing safety vests and garments.', category: 'reflective-tapes', features: ['Bright fluorescent colors', 'Durable polyester material', 'Used as base fabric for safety wear'], uses: ['Safety vests', 'High-visibility jackets', 'Bags and accessories'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/reflective-fabric.webp'] },
    { id: 'hi-reflective-tc-fabric', name: 'Hi-Reflective TC Fabric', shortDescription: 'Durable and comfortable Terylene/Cotton blend fabric for high-visibility workwear.', category: 'reflective-tapes', features: ['Breathable and strong TC blend', 'Fluorescent for daytime visibility', 'Ideal base for work uniforms'], uses: ['Work shirts and pants', 'Boiler suits', 'Durable safety garments'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/reflective-fabric.webp'] },
    { id: 'oxford-reflective-ribbon', name: 'Oxford Reflective Ribbon', shortDescription: 'Durable Oxford fabric ribbon with a central reflective stripe for sewing applications.', category: 'reflective-tapes', features: ['Strong Oxford fabric base', 'Central reflective stripe', 'Ideal for trimming and reinforcement'], uses: ['Trims on jackets and bags', 'Reinforcing seams on workwear', 'Pet accessories'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/reflective-ribbon.webp'] },
    { id: 'reflective-piping', name: 'Reflective Piping', shortDescription: 'Flexible reflective piping for sewing into seams to add contour visibility.', category: 'reflective-tapes', features: ['Adds reflective accents to seams', 'Flexible and easy to sew', 'Enhances product design'], uses: ['Athletic wear', 'Jackets and vests', 'Backpacks'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/reflective-piping.webp'] },
    { id: 'ordinary-reflective-polyester-fabric', name: 'Ordinary Reflective Polyester Fabric', shortDescription: 'Standard grade reflective polyester for cost-effective safety and fashion applications.', category: 'reflective-tapes', features: ['Economical choice', 'Good reflectivity', '100% polyester'], uses: ['Promotional items', 'Costumes', 'Casual wear'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/reflective-fabric.webp'] },
    { id: 'woven-reflective-ribbon', name: 'Woven Reflective Ribbon', shortDescription: 'Ribbon with reflective threads woven directly into the fabric for a premium look.', category: 'reflective-tapes', features: ['Integrated reflectivity', 'Soft and flexible', 'High-end appearance'], uses: ['Branded apparel', 'Lanyards', 'Fashion accents'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/reflective-ribbon.webp'] },
    { id: 'ordinary-reflective-tc-fabric', name: 'Ordinary Reflective TC Fabric', shortDescription: 'Standard grade Terylene/Cotton reflective fabric for general purpose use.', category: 'reflective-tapes', features: ['Good balance of cost and performance', 'Durable TC blend', 'Suitable for general workwear'], uses: ['General purpose safety vests', 'Utility worker uniforms', 'Event staff apparel'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/reflective-fabric.webp'] },

    // --- Double Sided Tapes ---
    { id: '3m-double-sided-foam-tape', name: '3M Double-Sided Foam Tape', shortDescription: 'Genuine 3M foam tapes for high-performance mounting and bonding in automotive and industrial applications.', category: 'double-sided-tapes', features: ['Conformable acrylic foam core', 'High shear strength', 'Resists weathering and moisture'], uses: ['Automotive emblems and trim', 'Signage and display mounting', 'Panel bonding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/3m-foam-tape.webp'] },
    { id: 'tissue-tape', name: 'Double-Sided Tissue Tape', shortDescription: 'Versatile tape with a non-woven tissue carrier, ideal for general purpose mounting and splicing.', category: 'double-sided-tapes', features: ['Hand-tearable', 'Good adhesion to various surfaces', 'Available with rubber or acrylic adhesive'], uses: ['Splicing paper and films', 'Mounting lightweight objects', 'Crafts and office use'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/tissue-tape.webp'] },
    { id: 'polyester-double-sided-tape', name: 'Polyester Double Sided Tape', shortDescription: 'Thin but strong double-sided tape with a polyester film carrier for laminating and mounting.', category: 'double-sided-tapes', features: ['High tensile strength', 'Dimensionally stable', 'Good temperature resistance'], uses: ['Laminating foams and fabrics', 'Mounting nameplates', 'Splicing films'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/polyester-tape.webp'] },
    { id: 'vhb-tape', name: 'VHB (Very High Bond) Double-Sided Tape', shortDescription: 'A powerful alternative to rivets and screws, providing a permanent bond for demanding applications.', category: 'double-sided-tapes', features: ['Extremely strong viscoelastic acrylic foam', 'Creates a permanent, durable seal', 'Resistant to temperature extremes, UV, and moisture', 'Absorbs shock and vibration'], uses: ['Panel to frame bonding', 'Automotive trim attachment', 'Architectural signage mounting', 'Electronics assembly'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/vhb-tape.webp'] },
    { id: 'lohmann-duploflex-tape', name: 'Lohmann DuploFLEX Tape', shortDescription: 'High-performance plate mounting tapes from Lohmann for the flexographic printing industry.', category: 'double-sided-tapes', features: ['Optimized foam density', 'Excellent print quality', 'Clean removal from plate and cylinder'], uses: ['Mounting photopolymer plates', 'Flexographic printing presses', 'Label and packaging printing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/lohmann-tape.webp'] },
    { id: 'pe-foam-tape', name: 'PE Foam Tape', shortDescription: 'Conformable closed-cell PE foam tape for mounting, sealing, and cushioning.', category: 'double-sided-tapes', features: ['Good gap-filling properties', 'Seals against dust and moisture', 'Available in various thicknesses'], uses: ['Mirror mounting', 'Gasketing applications', 'Sound dampening'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/pe-foam-tape.webp'] },
    { id: 'pet-double-sided-tape', name: 'PET Double-Sided Tape', shortDescription: 'A transparent, high-tack tape with a PET carrier, ideal for bonding plastics and smooth surfaces.', category: 'double-sided-tapes', features: ['Optically clear', 'High initial tack', 'Resistant to plasticizers'], uses: ['Mounting POS displays', 'Laminating transparent materials', 'Electronics assembly'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/pet-tape.webp'] },
    { id: 'transfer-tape', name: 'Transfer Tape', shortDescription: 'A pure adhesive film without a carrier, for excellent conformability and bonding to irregular surfaces.', category: 'double-sided-tapes', features: ['Unsupported adhesive film', 'Highly conformable', 'Available in various thicknesses'], uses: ['Graphic attachment', 'Laminating nameplates', 'Bonding gaskets'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/transfer-tape.webp'] },
    { id: 'acrylic-double-sided-tape', name: 'Acrylic Double Sided Tape', shortDescription: 'High-strength clear acrylic tape for permanent bonding of a wide range of materials.', category: 'double-sided-tapes', features: ['Transparent and durable', 'Excellent UV and temperature resistance', 'Creates a virtually invisible bond'], uses: ['Glass bonding', 'Architectural panel mounting', 'Automotive applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/acrylic-tape.webp'] },
    { id: 'double-sided-thermal-tape', name: 'Double-Sided Thermal Tape', shortDescription: 'Thermally conductive adhesive tape for bonding heat sinks to electronic components.', category: 'double-sided-tapes', features: ['Excellent thermal conductivity', 'Good dielectric strength', 'Provides both bond and heat transfer'], uses: ['Mounting heat sinks on CPUs and GPUs', 'LED lighting applications', 'Power transistors'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/thermal-tape.webp'] },
    { id: 'double-sided-scrim-tape', name: 'Double-Sided Scrim Tape', shortDescription: 'Reinforced with a fiberglass scrim for high shear strength and stability, ideal for flooring and insulation.', category: 'double-sided-tapes', features: ['Fiberglass reinforcement prevents stretching', 'High shear strength', 'Aggressive adhesive'], uses: ['Carpet and vinyl flooring installation', 'Insulation panel mounting', 'Splicing heavy materials'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/scrim-tape.webp'] },
    { id: 'eva-foam-tape', name: 'EVA Foam Tape', shortDescription: 'Economical and versatile EVA foam tape for general-purpose mounting and sealing.', category: 'double-sided-tapes', features: ['Cost-effective solution', 'Good cushioning and sealing properties', 'Adheres to a variety of surfaces'], uses: ['Lightweight mounting', 'Weatherstripping', 'Dust sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/eva-foam-tape.webp'] },
    { id: 'spacer-tapes', name: 'Spacer Tapes', shortDescription: 'Double-sided foam tapes used in structural glazing to maintain spacing and alignment.', category: 'double-sided-tapes', features: ['Open-cell polyurethane or PVC foam', 'Compatible with structural silicones', 'Ensures correct sealant depth'], uses: ['Structural silicone glazing', 'Curtain wall systems', 'Window manufacturing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/spacer-tape.webp'] },
    { id: 'nano-magic-tape', name: 'Nano Magic Tape', shortDescription: 'A reusable, transparent, double-sided gel tape that can be washed and reused multiple times.', category: 'double-sided-tapes', features: ['Washable and reusable', 'Strong adhesion', 'Leaves no residue'], uses: ['Temporary mounting of pictures', 'Holding down rugs', 'Organizing cables'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/nano-tape.webp'] },
    { id: 'hot-melt-tissue-tapes', name: 'Hot Melt Tissue Tapes', shortDescription: 'Double-sided tissue tape with a hot-melt adhesive for very high initial tack.', category: 'double-sided-tapes', features: ['Extremely high initial grab', 'Good for rough and porous surfaces', 'Economical'], uses: ['Carpet installation', 'Splicing corrugated materials', 'Foam bonding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/hot-melt-tissue-tape.webp'] },
    { id: 'double-sided-cloth-tape', name: 'Double Sided Cloth Tape', shortDescription: 'A high-strength double-sided tape with a cloth carrier for demanding applications.', category: 'double-sided-tapes', features: ['Strong and conformable cloth backing', 'High adhesion and shear strength', 'Tears by hand'], uses: ['Exhibition carpet laying', 'Stereo mounting in printing', 'Heavy-duty bonding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/double-cloth-tape.webp'] },
    { id: 'acrylic-gel-tape', name: 'Acrylic Gel Tape', shortDescription: 'A solid acrylic gel tape providing a super-strong, transparent, and weatherproof bond.', category: 'double-sided-tapes', features: ['Similar to VHB tape', 'Waterproof and UV resistant', 'Bonds to metal, glass, and plastics'], uses: ['Automotive accessories', 'Outdoor sign mounting', 'Glass partition bonding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/acrylic-tape.webp'] },
    { id: 'xlpe-foam-tapes', name: 'XLPE Foam Tapes', shortDescription: 'Cross-linked polyethylene foam tape for superior sealing and insulation properties.', category: 'double-sided-tapes', features: ['Excellent thermal and acoustic insulation', 'Resistant to chemicals and moisture', 'Durable and resilient'], uses: ['HVAC gasketing', 'Automotive sealing', 'Appliance manufacturing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/xlpe-foam-tape.webp'] },

    // --- Specialty Tapes ---
    { id: 'masking-tape', name: 'Masking Tape', shortDescription: 'General purpose and high-temperature masking tapes for painting, powder coating, and bundling.', category: 'specialty-tapes', features: ['Crepe paper backing', 'Removes cleanly', 'Available in different temperature ratings'], uses: ['Automotive painting', 'General purpose masking', 'Light bundling'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/masking-tape.webp'] },
    { id: 'bopp-tape', name: 'BOPP Tape', shortDescription: 'Biaxially Oriented Polypropylene (BOPP) tape for reliable carton sealing and packaging.', category: 'specialty-tapes', features: ['Strong and durable', 'Available in clear, brown, and custom printed', 'Acrylic or hot-melt adhesive'], uses: ['Carton and box sealing', 'General purpose packaging', 'Bundling'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/bopp-tape.webp'] },
    { id: 'aluminium-foil-tape', name: 'High-Performance Aluminium Foil Tape', shortDescription: 'Ideal for HVAC duct sealing, thermal insulation, and heat shielding applications with a durable seal.', category: 'specialty-tapes', features: ['Thermally conductive', 'Resistant to moisture, chemicals, and flame', 'High-performance acrylic adhesive', 'Conforms to irregular surfaces'], uses: ['HVAC duct sealing and joining', 'Masking in paint stripping', 'Heat shielding for sensitive components', 'Waterproofing and sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/aluminium-foil-tape.webp'] },
    { id: 'cloth-duct-tape', name: 'Heavy-Duty Cloth Duct Tape', shortDescription: 'A strong, conformable, and water-resistant tape for sealing, bundling, and general repairs.', category: 'specialty-tapes', features: ['Strong polyethylene-coated cloth', 'Aggressive natural rubber adhesive', 'Water and abrasion-resistant'], uses: ['HVAC duct sealing', 'Heavy-duty bundling', 'Temporary repairs', 'Bookbinding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/cloth-duct-tape.webp'] },
    { id: 'high-temperature-sealing-tape', name: 'High Temperature Sealing Tape', shortDescription: 'Specialty tapes designed to create seals in high-temperature environments like ovens and engines.', category: 'specialty-tapes', features: ['Made from materials like fiberglass or silicone', 'Maintains seal integrity at high temperatures', 'Chemical resistant'], uses: ['Sealing oven doors', 'Engine gasketing', 'Industrial furnace sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/high-temp-sealing.webp'] },
    { id: 'paper-tape', name: 'Paper Tape', shortDescription: 'General purpose paper tapes for light packaging, crafts, and office use.', category: 'specialty-tapes', features: ['Eco-friendly option', 'Hand-tearable', 'Good for writing on'], uses: ['Picture framing', 'Art and craft projects', 'Light-duty carton sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/paper-tape.webp'] },
    { id: 'silicone-tape', name: 'Silicone Tape', shortDescription: 'Self-fusing silicone tape that creates a permanent, waterproof seal by amalgamating to itself.', category: 'specialty-tapes', features: ['Self-fusing, no adhesive', 'Excellent insulation properties', 'Resists high temperatures and pressures'], uses: ['Emergency pipe and hose repair', 'Electrical wire insulation', 'Tool handle grips'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/silicone-tape.webp'] },
    { id: 'polyester-tape', name: 'Polyester Tape', shortDescription: 'Single-sided polyester tape with silicone or acrylic adhesive for high-temperature masking.', category: 'specialty-tapes', features: ['Strong polyester film backing', 'Clean removal at high temperatures', 'Available in various colors'], uses: ['Powder coating masking', 'Anodizing and e-coating', 'Splicing silicone-coated papers'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/polyester-tape.webp'] },
    { id: 'pvc-pipe-wrapping-tape', name: 'PVC Pipe Wrapping Tape', shortDescription: 'Durable PVC tape for protecting underground pipes and conduits from corrosion.', category: 'specialty-tapes', features: ['Resistant to moisture, acids, and alkalis', 'Provides excellent insulation', 'Conformable for easy wrapping'], uses: ['Protecting buried pipelines', 'Corrosion protection for metal conduits', 'Insulating electrical joints'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/pvc-pipe-wrap.webp'] },
    { id: 'bag-sealing-tape', name: 'Bag Sealing Tape', shortDescription: 'Colored PVC tape used with a dispenser for quick and easy sealing of produce and bakery bags.', category: 'specialty-tapes', features: ['Strong and reliable seal', 'Available in multiple colors for coding', 'Used with bag sealing dispensers'], uses: ['Sealing poly bags in supermarkets', 'Bakery and food packaging', 'Industrial bag closure'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/bag-sealing-tape.webp'] },
    { id: 'acetate-cloth-tape', name: 'Acetate Cloth Tape', shortDescription: 'A conformable, printable tape with excellent insulation properties for electrical applications.', category: 'specialty-tapes', features: ['High dielectric strength', 'Printable surface', 'Resistant to oils and solvents'], uses: ['Coil and transformer wrapping', 'Wire harnessing', 'Motor insulation'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/acetate-tape.webp'] },
    { id: 'sticky-mat', name: 'Sticky Mat', shortDescription: 'Multi-layered adhesive mats placed at entrances to remove contaminants from footwear.', category: 'specialty-tapes', features: ['Peel-off disposable sheets', 'Captures dirt and dust effectively', 'Non-skid backing'], uses: ['Cleanroom entrances', 'Hospitals and labs', 'Construction sites to control dust'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/sticky-mat.webp'] },
    { id: 'fine-line-masking-tape', name: 'Fine Line Masking Tape', shortDescription: 'Thin vinyl or polyester tape for creating sharp, precise paint lines in custom auto body and design work.', category: 'specialty-tapes', features: ['Creates sharp, clean paint edges', 'Flexible for curves and contours', 'Resists paint bleed'], uses: ['Custom automotive painting', 'Architectural design', 'Industrial painting'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/fine-line-tape.webp'] },
    { id: 'mica-tape', name: 'Mica Tape', shortDescription: 'High-temperature insulation tape made from mica paper, providing excellent fire resistance for cables.', category: 'specialty-tapes', features: ['Excellent thermal and electrical insulation', 'Fire resistant properties', 'Used in high-voltage applications'], uses: ['Insulating high-voltage cables', 'Fire survival cables', 'Induction furnaces'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/mica-tape.webp'] },
    { id: 'green-polyester-tape', name: 'Green Polyester Tape', shortDescription: 'A common choice for high-temperature masking due to its visibility and clean removal.', category: 'specialty-tapes', features: ['High visibility green color', 'Silicone adhesive for clean removal', 'Temperature resistant up to 200°C'], uses: ['Powder coating', 'Anodizing', 'Splicing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/green-polyester-tape.webp'] },
    { id: 'green-polyester-tape-with-liner', name: 'Green Polyester Tape with Liner', shortDescription: 'Same as green polyester tape but with a release liner, making it suitable for die-cutting.', category: 'specialty-tapes', features: ['Release liner for easy handling', 'Can be die-cut into custom shapes', 'High-temperature masking'], uses: ['Die-cut masking parts', 'Precise masking applications', 'Electronics assembly'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/green-polyester-tape.webp'] },
    { id: 'thermal-conductive-pads', name: 'Thermal Conductive Pads', shortDescription: 'Soft, conformable pads that transfer heat between components and heat sinks.', category: 'specialty-tapes', features: ['High thermal conductivity', 'Fills air gaps effectively', 'Electrically isolating'], uses: ['Between CPUs and heat sinks', 'LED lighting modules', 'Power supplies'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/thermal-pad.webp'] },
    { id: 'pe-surface-protection-film', name: 'PE Surface Protection Film', shortDescription: 'A temporary protective film to prevent scratches and dirt on surfaces during manufacturing and transit.', category: 'specialty-tapes', features: ['Removes cleanly without residue', 'Available in various tack levels', 'Protects against abrasion and scratches'], uses: ['Protecting stainless steel and aluminum sheets', 'Guarding plastic surfaces', 'Protecting glass and screens'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/protection-film.webp'] },
    { id: 'powder-coated-tape', name: 'Powder Coated Tape', shortDescription: 'High-temperature tapes specifically designed to withstand the powder coating process.', category: 'specialty-tapes', features: ['Resists high curing temperatures', 'Clean removal, no residue', 'Polyester or polyimide backing'], uses: ['Masking parts during powder coating', 'Protecting threads and holes'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/powder-coating-tape.webp'] },
    { id: 'lamination-tape', name: 'Lamination Tape', shortDescription: 'Thin, optically clear tapes used for laminating nameplates, graphics, and touch screens.', category: 'specialty-tapes', features: ['Optically clear adhesive', 'Provides a protective layer', 'Strong bond to various substrates'], uses: ['Graphic overlays', 'Touchscreen assembly', 'Nameplate manufacturing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/lamination-tape.webp'] },
    { id: 'aluminium-foil-scrim-kraft-tape-fsk', name: 'Aluminium Foil Scrim Kraft Tape (FSK)', shortDescription: 'A foil, scrim, and kraft paper laminate tape for demanding HVAC insulation and duct sealing.', category: 'specialty-tapes', features: ['High tensile strength due to scrim reinforcement', 'Excellent vapor barrier', 'Flame retardant'], uses: ['Sealing insulation joints in HVAC', 'Duct board sealing', 'High-performance insulation applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/fsk-tape.webp'] },
    { id: 'aluminium-pet-tape-alupet', name: 'Aluminium PET Tape (Alupet)', shortDescription: 'A laminate of aluminum foil and polyester film, providing both shielding and strength.', category: 'specialty-tapes', features: ['Provides EMI/RFI shielding', 'High mechanical strength', 'Used in cable manufacturing'], uses: ['Cable shielding', 'Insulation applications', 'Shielded room construction'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/alupet-tape.webp'] },
    { id: 'aluminium-butyl-tape', name: 'Aluminium Butyl Tape', shortDescription: 'A foil-backed tape with a very thick butyl rubber adhesive for instant, waterproof seals.', category: 'specialty-tapes', features: ['Extremely strong, permanent bond', 'Waterproof and weatherproof', 'Adheres to almost any surface'], uses: ['Roof and gutter repair', 'Sealing joints in caravans and vehicles', 'HVAC duct sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/butyl-tape.webp'] },
    { id: 'fiber-glass-cloth-tape', name: 'Fiber Glass Cloth Tape', shortDescription: 'High-strength fiberglass tape with excellent temperature resistance for demanding applications.', category: 'specialty-tapes', features: ['High tensile strength', 'Abrasion resistant', 'High-temperature adhesive'], uses: ['High-temperature duct sealing', 'Coil insulation', 'Reinforcing and repairing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/fiber-glass-tape.webp'] },
    { id: 'nbr-foam-tapes', name: 'NBR Foam Tapes', shortDescription: 'Nitrile Butadiene Rubber (NBR) foam tapes for excellent sealing and insulation against oil and chemicals.', category: 'specialty-tapes', features: ['Excellent resistance to oil, fuel, and chemicals', 'Good sealing and cushioning', 'Flexible and conformable'], uses: ['Automotive gaskets and seals', 'Industrial sealing applications', 'HVAC systems'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/nbr-foam-tape.webp'] },
    { id: 'air-vent-tape', name: 'Air Vent Tape', shortDescription: 'Specialized tape used to seal multi-wall polycarbonate sheets, preventing dust and moisture entry while allowing ventilation.', category: 'specialty-tapes', features: ['Allows condensation to escape', 'Filters out dust and insects', 'Ensures clarity of polycarbonate sheets'], uses: ['Sealing greenhouse panels', 'Conservatory roofs', 'Polycarbonate constructions'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/air-vent-tape.webp'] },
    { id: 'pink-rayon-tape', name: 'Pink Rayon Tape', shortDescription: 'A specialized, high-temperature, flatback paper tape used in the electrical industry.', category: 'specialty-tapes', features: ['High-temperature resistance', 'High dielectric strength', 'Printable'], uses: ['Outer wrap for capacitors and coils', 'Transformer insulation', 'Wire harnessing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/pink-rayon-tape.webp'] },
    { id: 'yellow-polyester-tape', name: 'Yellow Polyester Tape', shortDescription: 'A visible polyester tape used for electrical insulation and layer separation in transformers.', category: 'specialty-tapes', features: ['High visibility', 'Excellent dielectric strength', 'UL recognized'], uses: ['Core, layer, and final insulation', 'Transformer and motor manufacturing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/yellow-polyester-tape.webp'] },
    { id: 'aluminium-glass-tape-fr-grade', name: 'Aluminium Glass Tape (FR Grade)', shortDescription: 'A laminate of aluminum foil and glass cloth, providing extreme heat resistance and strength.', category: 'specialty-tapes', features: ['Flame retardant', 'Reflects radiant heat', 'High tensile strength'], uses: ['Heat shielding for cables and hoses', 'Aerospace applications', 'Industrial furnace repair'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/aluminium-glass-tape.webp'] },
    { id: 'pvc-pipe-wrapping-tape-without-adhesive', name: 'PVC Pipe Wrapping Tape (Without Adhesive)', shortDescription: 'A non-adhesive PVC tape that clings to itself for wrapping pipes and cables.', category: 'specialty-tapes', features: ['Non-adhesive, self-clinging', 'Flexible and conformable', 'Protects against corrosion and abrasion'], uses: ['Wrapping automotive wiring harnesses', 'Protecting industrial pipes', 'Handle grips'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/pvc-pipe-wrap.webp'] },
    { id: 'glass-cloth-tape', name: 'Glass Cloth Tape', shortDescription: 'High-strength, high-temperature tape made from glass cloth for electrical insulation and mechanical protection.', category: 'specialty-tapes', features: ['Extremely high tensile strength', 'Abrasion resistant', 'High-temperature silicone adhesive'], uses: ['Permanent sealing of high-temp ducts', 'Motor and transformer insulation', 'Plasma spray masking'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/glass-cloth-tape.webp'] },
    { id: 'glass-cloth-tape-fr-grade', name: 'Glass Cloth Tape (FR Grade)', shortDescription: 'Flame-retardant version of glass cloth tape for applications requiring fire resistance.', category: 'specialty-tapes', features: ['Meets flame retardancy specifications', 'High temperature and strength', 'Ideal for aerospace and marine'], uses: ['Aircraft wire harnessing', 'Sealing panels in aerospace', 'Shipboard cable bundling'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/glass-cloth-tape.webp'] },
    { id: 'filament-tapes', name: 'Filament Tapes', shortDescription: 'High-tensile strength tape reinforced with fiberglass filaments for heavy-duty bundling and strapping.', category: 'specialty-tapes', features: ['Extremely high tensile strength', 'Resistant to tears and splitting', 'Available in mono and cross-weave'], uses: ['Palletizing and bundling heavy goods', 'Securing appliance parts during transit', 'Pipe and beam reinforcement'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/filament-tape.webp'] },
    { id: 'ez-application-tape', name: 'EZ Application Tape', shortDescription: 'A paper-based tape used to transfer vinyl graphics and decals from the liner to the final surface.', category: 'specialty-tapes', features: ['Medium to high tack levels', 'Lays flat for easy application', 'Tears cleanly'], uses: ['Vinyl sign making', 'Transferring cut graphics', 'Protecting graphics during application'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/application-tape.webp'] },
    { id: 'kraft-paper-tape', name: 'Kraft Paper Tape', shortDescription: 'An eco-friendly, self-adhesive paper tape for carton sealing.', category: 'specialty-tapes', features: ['Recyclable and biodegradable', 'Strong bond to cardboard', 'Can be written on'], uses: ['Eco-friendly packaging', 'Picture framing', 'General carton sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/kraft-tape.webp'] },
    { id: 'reinforcement-kraft-paper-tape', name: 'Reinforcement Kraft Paper Tape', shortDescription: 'Kraft paper tape reinforced with fiberglass filaments for extra strength.', category: 'specialty-tapes', features: ['Combines strength of filament with paper backing', 'High tensile strength', 'Eco-friendly option'], uses: ['Sealing heavy or over-stuffed cartons', 'Bundling heavy items', 'Reinforcement applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/reinforced-kraft-tape.webp'] },
    { id: 'water-activated-kraft-paper-tape', name: 'Water Activated Kraft Paper Tape', shortDescription: 'Also known as gummed tape, it creates a permanent, tamper-evident bond once activated with water.', category: 'specialty-tapes', features: ['Creates a destructive bond with cardboard', 'Tamper-evident seal', 'Often reinforced with fiberglass'], uses: ['High-security carton sealing', 'Packaging for high-value items', 'Automated packaging lines'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/water-activated-tape.webp'] },
    { id: 'adhesive-cloth-tape', name: 'Adhesive Cloth Tape', shortDescription: 'A versatile, conformable cloth tape for a wide range of applications including bookbinding and gaffing.', category: 'specialty-tapes', features: ['Strong and flexible cloth backing', 'Available in multiple colors', 'Clean removal (gaffer type) or permanent'], uses: ['Bookbinding', 'Gaffer tape for film and stage', 'General repairs and bundling'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/cloth-duct-tape.webp'] },

    // --- PTFE & Teflon Tapes ---
    { id: 'ptfe-coated-fiberglass-fabric-non-adhesive', name: 'Non-Adhesive PTFE Coated Fiberglass Fabric', shortDescription: 'High-temperature, non-stick fabric used as a reusable release sheet in various industrial processes.', category: 'teflon-ptfe-tapes', features: ['Extreme temperature resistance (-73°C to 260°C)', 'Superior non-stick surface', 'High tensile strength'], uses: ['Release sheets for heat pressing', 'Conveyor belts', 'Gaskets and seals'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/ptfe-fabric.webp'] },
    { id: 'ptfe-silicone-adhesive-tape', name: 'PTFE (Teflon) Coated Tape with Silicone Adhesive', shortDescription: 'Provides a non-stick, low-friction surface for heat sealing machines, chutes, and guide rails.', category: 'teflon-ptfe-tapes', features: ['High-temperature resistance', 'Excellent non-stick properties', 'Low coefficient of friction', 'Chemical resistant'], uses: ['Heat sealing equipment', 'Lining chutes and hoppers', 'Mold release applications', 'Covering rollers'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/ptfe-tape.webp'] },
    { id: 'ptfe-coated-fiberglass-fabric-with-silicone-adhesive', name: 'PTFE Coated Fiberglass Fabric with Silicone Adhesive', shortDescription: 'A durable, adhesive-backed version of our PTFE fabric for easy application.', category: 'teflon-ptfe-tapes', features: ['Combines PTFE properties with adhesive backing', 'High temperature silicone adhesive', 'Durable fiberglass reinforcement'], uses: ['Lining work surfaces', 'Covering heat sealer elements', 'Creating non-stick surfaces'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/ptfe-tape.webp'] },
    { id: 'ptfe-coated-fiberglass-fabric-with-silicone-adhesive-liner', name: 'PTFE Coated Fiberglass Fabric with Liner', shortDescription: 'Same as our adhesive PTFE fabric, but with a release liner for die-cutting and precise application.', category: 'teflon-ptfe-tapes', features: ['Yellow corrugated release liner', 'Suitable for die-cutting custom shapes', 'High-performance non-stick surface'], uses: ['Die-cut gaskets and pads', 'Applications requiring precise placement', 'Advanced manufacturing processes'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/ptfe-tape.webp'] },

    // --- Antistatic & ESD Tapes ---
    { id: 'kapton-tape', name: 'High-Temperature Kapton Polyimide Tape', shortDescription: 'Ideal for high-temperature masking in electronics, wave soldering, and powder coating.', category: 'antistatic-esd-tapes', features: ['Polyimide film with silicone adhesive', 'Withstands temperatures up to 260°C (500°F)', 'Removes cleanly with no residue', 'Excellent dielectric strength'], uses: ['PCB masking during wave soldering', 'Electrical insulation for transformers and motors', '3D printer bed surface', 'High-temperature powder coating'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/kapton-tape.webp'] },
    { id: 'polyimide-tape', name: 'Polyimide Tape', shortDescription: 'High-performance polyimide film tape with silicone adhesive, also known as Kapton tape.', category: 'antistatic-esd-tapes', features: ['Excellent thermal and electrical insulation', 'High temperature resistance', 'Dimensionally stable'], uses: ['Electronics manufacturing', 'Aerospace applications', 'Automotive sensors'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/kapton-tape.webp'] },
    { id: 'emi-shielding-tape', name: 'EMI Shielding Tape', shortDescription: 'Tapes made from conductive materials like copper or aluminum foil to block electromagnetic interference.', category: 'antistatic-esd-tapes', features: ['Available with conductive adhesive', 'Provides effective shielding against EMI/RFI', 'Flexible and conformable'], uses: ['Shielding cables and connectors', 'Enclosing electronic components', 'Grounding applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/emi-tape.webp'] },
    { id: 'copper-foil-tape', name: 'Conductive Copper Foil Tape for EMI Shielding', shortDescription: 'Single-sided copper tape with conductive adhesive for EMI/RFI shielding, grounding, and PCB repair.', category: 'antistatic-esd-tapes', features: ['Highly conductive copper foil', 'Aggressive conductive acrylic adhesive', 'Solderable and flexible', 'Excellent for grounding and shielding'], uses: ['EMI/RFI shielding in electronics', 'Grounding electrical cabinets', 'Slug and snail barrier in gardening', 'Stained glass crafting'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/copper-foil-tape.webp'] },
    { id: 'conductive-grid-tape', name: 'ESD Conductive Grid Tape', shortDescription: 'Three-layer tape with a conductive grid, ideal for sealing ESD bags and packaging in static-sensitive areas.', category: 'antistatic-esd-tapes', features: ['Low static generation', 'Buried conductive grid layer', 'Clear for visibility of contents'], uses: ['Sealing ESD shielding bags', 'Use in cleanrooms and EPAs', 'Office use in static-sensitive areas'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/conductive-grid-tape.webp'] },
    { id: 'esd-kapton-tape', name: 'ESD Kapton Tape', shortDescription: 'Polyimide tape with antistatic properties, designed for masking PCBs in static-sensitive environments.', category: 'antistatic-esd-tapes', features: ['Combines high-temp resistance with ESD safety', 'Low static discharge', 'Clean removal'], uses: ['Masking PCBs before wave soldering in an EPA', 'High-temperature static-sensitive applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/esd-kapton-tape.webp'] },
    { id: 'anti-static-polyester-tape', name: 'Anti-Static Polyester Tape', shortDescription: 'Polyester tape treated with an anti-static coating for use in electronics assembly.', category: 'antistatic-esd-tapes', features: ['Low static properties', 'Silicone adhesive', 'For general use in EPAs'], uses: ['Sealing containers in cleanrooms', 'General purpose bundling in static-sensitive areas'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/anti-static-poly-tape.webp'] },
    { id: 'polyimide-double-sided-tape', name: 'Polyimide Double-Sided Tape', shortDescription: 'A high-temperature double-sided tape using polyimide film as a carrier for stability.', category: 'antistatic-esd-tapes', features: ['High temperature resistance on both sides', 'Dimensionally stable carrier', 'For bonding components in hot environments'], uses: ['Mounting components inside electronics before reflow soldering', 'High-temp splicing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/double-polyimide-tape.webp'] },
    { id: 'polyimide-film-tape', name: 'Polyimide Film Tape', shortDescription: 'General purpose polyimide film tape, also known as Kapton tape, for high-temperature applications.', category: 'antistatic-esd-tapes', features: ['Amber colored polyimide film', 'Silicone adhesive', 'Resists up to 260°C'], uses: ['Electrical insulation', 'High-temperature masking', '3D printing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/kapton-tape.webp'] },
    { id: 'tin-plated-copper-tape', name: 'Tin-Plated Copper Tape', shortDescription: 'Copper foil tape plated with tin for enhanced corrosion resistance and solderability.', category: 'antistatic-esd-tapes', features: ['Tin plating prevents oxidation', 'Excellent solderability', 'Conductive adhesive for EMI shielding'], uses: ['EMI/RFI shielding in corrosive environments', 'Soldering and PCB repair', 'Marine electronics'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/product-images/tin-copper-tape.webp'] },
];
