import { Industry, NavLinkData, Testimonial, Product, Category, IndustryDetail } from './types';

export const NAV_LINKS: NavLinkData[] = [
    { name: 'Home', path: '/' },
    { name: 'About Us', path: '/about' },
    { name: 'Industries', path: '/industries' },
    { name: 'Products', path: '/products' },
    { name: 'Blog', path: '/blog' },
    { name: 'Contact', path: '/contact' },
    { name: 'Request a Quote', path: '/request-quote', isButton: true },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
    {
        quote: "Tape India's VHB tapes have revolutionized our assembly process. The bond is incredibly strong, and their technical support is top-notch.",
        author: "Ravi Sharma",
        company: "Lead Engineer, Auto Components Ltd."
    },
    {
        quote: "The quality and consistency of their packaging tapes have significantly reduced our shipping damages. A reliable partner for our logistics.",
        author: "Priya Menon",
        company: "Supply Chain Manager, E-commerce Giant"
    },
    {
        quote: "We rely on their high-temperature masking tapes for our powder coating line. They perform flawlessly and remove cleanly every time.",
        author: "Anil Kumar",
        company: "Production Head, Metal Fabricators Inc."
    }
];

export const INDUSTRIES: Industry[] = [
    { 
        id: 'packaging-industry', 
        name: 'Packaging', 
        subtitle: 'Sealing, bundling, and safety.',
        icon: 'BoxIcon',
        gradientClasses: 'from-amber-500 via-orange-600 to-red-700',
    },
    { 
        id: 'hvac-industry', 
        name: 'HVAC',
        subtitle: 'Duct sealing & thermal control.',
        icon: 'WindIcon',
        gradientClasses: 'from-cyan-500 via-cyan-600 to-blue-700',
    },
    { 
        id: 'print-labels-signage-industry', 
        name: 'Print & Signage',
        subtitle: 'Mounting, printing, and bonding.',
        icon: 'LayersIcon',
        gradientClasses: 'from-slate-500 via-slate-600 to-slate-700',
    },
    { 
        id: 'electronic-industry', 
        name: 'Electronics',
        subtitle: 'Shielding & high-temp solutions.',
        icon: 'CpuIcon',
        gradientClasses: 'from-blue-600 via-blue-700 to-indigo-800',
        highlight: true
    },
    { 
        id: 'reflective-safety-industry', 
        name: 'Reflective & Safety',
        subtitle: 'High-visibility tapes and fabrics.',
        icon: 'SunIcon',
        gradientClasses: 'from-yellow-400 via-yellow-500 to-orange-500',
    },
    { 
        id: 'ptfe-teflon-industry', 
        name: 'PTFE & Teflon',
        subtitle: 'High-temperature, non-stick.',
        icon: 'SparklesIcon',
        gradientClasses: 'from-green-500 via-green-600 to-teal-700',
    },
];

export const INITIAL_INDUSTRIES_DETAILED: IndustryDetail[] = [
    {
        id: 'packaging-industry',
        name: 'Packaging Industry',
        description: 'Our tapes provide secure sealing, bundling, and protection for all types of packaging. From standard carton sealing to tamper-evident solutions, we ensure your products arrive safely.',
        products: [
            'hazardtape', 'floor-marking-tape', 'coloured-anti-slip-tape', 'caution-tape', 
            'barricade-tape', 'tamper-proof-tape-1', 'nastro-heavy-duty-floor-marking', 
            'glowindark', 'anti-skid-glow-in-dark', 'esd-floor-marking', 
            'glowindark-marking', 'anti-skid', 'anti-slip-bathroom', 
            'vhb-tape', 'hot-melt-tissue-tape', 'acrylic-double-sided-tape-1', 'aacrylic-gel-tape-1', 
            'masking-tape', 'bopp-tape', 'aluminum-foil-2-tape', 'kapton-tape', 'duct-tape', 
            'high-sealing-tape', 'bag-sealing-tape', 'acetate-cloth-tape-white-19mm-x-66m-crop', 'fine-line-masking-tape', 
            'green-polyster', 'green-polyster-with-liner', 'surface-protection-tape', 
            'lamination-tape', 'filament-tape', 'ez-application-tape', 'kraft-paper-tape', 
            'reinforced-paper-tapes1', 'water-activated-kraft-tape', 'cloth-adhesive-tape-500x500-1', 
            'ptfe-silicone-adhesive', 'ptfe-fiberglass-with-silicone-adhesive', 
            'emi-sheliding-tape', 'copper-tape-2', 'polyimide-film-tape', 'tin-copper-tape', 
            'air-vent-tape', 'pink-rayon'
        ],
        seo: {
            title: "Packaging Tapes Manufacturer | Carton Sealing Solutions",
            description: "Tape India supplies a complete range of packaging tapes, including BOPP, filament, and water-activated tapes for secure carton sealing. B2B supplier."
        }
    },
    {
        id: 'hvac-industry',
        name: 'HVAC Industry',
        description: 'We offer a complete range of tapes for the HVAC industry, including foil tapes for duct sealing, insulation tapes for thermal control, and specialized sealing solutions to ensure system efficiency.',
        products: [
            'double-sided-scrim-tape', 'eva-foam-tape', 'spacer-tape', 'xlpe-foam-tapes', 
            'aluminum-foil-2-tape', 'duct-tape', 'pvc-pipe-tape-1', 'foil-scrim-kraft-tape', 
            'aluminium-pet', 'butyl', 'fiberglass-tape', 
            'nrm-foam-tape', 'aluminium-fr-grade', 'red-pvc-non-adhesive-tape', 
            'glass-cloth-tape', 'fr-grade-glass-cloth-tape'
        ],
        seo: {
            title: "HVAC Tapes Supplier | Duct Sealing & Insulation Tapes",
            description: "Find high-performance HVAC tapes at Tape India. We supply aluminum foil, FSK, and duct tapes for sealing and insulation. Get a quote for your project."
        }
    },
    {
        id: 'print-labels-signage-industry',
        name: 'Print, Labels & Signage Industry',
        description: 'Our tapes are essential for the printing and signage industries, offering solutions for plate mounting, splicing, laminating, and permanent sign mounting with high-performance double-sided tapes.',
        products: [
            'photoluminescent-film', '3m-foam-foam-tape', 'tissue-tape', 'polyester-double-side', 
            'vhb-tape', 'lohmann', 'pet-double-sided-tape', 'transfer-tape', 
            'acrylic-double-sided-tape-1', 'silicone-tape', 'hot-melt-tissue-tape', 'double-coated-cloth-tape-581', 
            'aacrylic-gel-tape-1', 'paper-tape', 'bag-sealing-tape', 'acetate-cloth-tape-white-19mm-x-66m-crop', 
            'surface-protection-tape', 'lamination-tape', 'ez-application-tape'
        ],
        seo: {
            title: "Tapes for Printing & Signage | Plate Mounting & Bonding",
            description: "Tape India offers a range of tapes for the print and signage industry, including plate mounting, double-sided, and application tapes. B2B solutions."
        }
    },
    {
        id: 'electronic-industry',
        name: 'Electronics Industry',
        description: 'Protect sensitive components with our range of high-performance tapes for the electronics industry. We provide solutions for EMI shielding, high-temperature masking, thermal management, and ESD protection.',
        products: [
            'esd-floor-marking', '3m-foam-foam-tape', 'polyester-double-side', 
            'pet-double-sided-tape', 'transfer-tape', 'double-sided-thermal-tape', 'double-sided-scrim-tape', 
            'eva-foam-tape', 'spacer-tape', 'xlpe-foam-tapes', 'kapton-tape', 'stickymat', 'mica-tape', 
            'green-polyster', 'green-polyster-with-liner', 'thermal-condu-pads', 
            'fiberglass-tape', 'nrm-foam-tape', 'pink-rayon', 'yellow-polyester', 
            'glass-cloth-tape', 'fr-grade-glass-cloth-tape', 'polyimide-tape', 'emi-sheliding-tape', 
            'copper-tape-2', 'conductive-grind-tape', 'esd-kapton', 'anti-static-polyester-tape', 
            'double-sided-polyimide-tapes-1', 'polyimide-film-tape', 'tin-copper-tape'
        ],
        seo: {
            title: "Electronics Tapes | Kapton, ESD & Shielding Tapes | Tape India",
            description: "Source high-performance tapes for electronics manufacturing. We supply Kapton, ESD, thermal, and EMI shielding tapes. Contact Tape India for a quote."
        }
    },
    {
        id: 'reflective-safety-industry',
        name: 'Reflective & Safety Industry',
        description: 'We are a leading supplier of reflective and safety materials for apparel and equipment. Our range includes sew-on tapes, heat transfer films, and high-visibility fabrics to meet stringent safety standards.',
        products: [
            'silver-tc', 'heattransfer', 'heat-transfer-reflective-vinyl-film-tape-heat-transfer-segmented-reflective-tape',
            'pvc-reflective-tape', 'grey-reflective-yarn-2-0-mm-double-side-500x500-1', 'material-fr-reflective-tape-all-1', 
            'high-reflective-polyester', 'hipoloyster', 'oxfordrefle', 
            'grey-reflective-piping', 'ordinary-polyster-fabric', 'woven', 
            'ordinary-reflective-tc-fabric'
        ],
        seo: {
            title: "Reflective Tapes & Safety Fabrics Supplier | Tape India",
            description: "Tape India is a B2B supplier of reflective tapes and fabrics for the safety apparel industry. We offer sew-on, heat transfer, and FR options. Get a quote."
        }
    },
    {
        id: 'ptfe-teflon-industry',
        name: 'PTFE & Teflon Industry',
        description: 'Our PTFE and Teflon tapes provide superior non-stick, high-temperature, and low-friction surfaces for demanding industrial processes like heat sealing, mold release, and conveyor applications.',
        products: [
            'ptfe-coated-fabric-non-adhesive-1', 'ptfe-silicone-adhesive', 
            'ptfe-fiberglass-with-silicone-adhesive', 'ptfe-coated-fiberglass-fabric-with-silicone-adhesive-liner'
        ],
        seo: {
            title: "PTFE & Teflon Tape Manufacturer | High-Temp Non-Stick Tapes",
            description: "Buy high-temperature, non-stick PTFE and Teflon tapes from Tape India. Ideal for heat sealing, mold release, and industrial non-stick applications."
        }
    },
];

// This is the definitive source for all product CONTENT.
// It will be merged with SEO data from seoData.ts.
export const PRODUCTS: Omit<Product, 'seo'>[] = [
    // --- Safety Tapes ---
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'hazardtape', name: 'Hazard Warning & Safety Stripe Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/hazardtape.webp', shortDescription: 'Hazard Warning & Safety Stripe Tape by Tape India is used to mark danger areas, restricted pathways, and accident-prone zones in factories and warehouses. Its thick PVC backing resists abrasion from heavy foot traffic, forklifts, and machine movement. The yellow-black stripes provide high visibility even in low-light areas. Suitable for safety compliance and industrial floor demarcation.', category: 'safety-tapes', features: ['High-contrast colors (Black/Yellow, Red/White)', 'Strong PVC backing for durability', 'Aggressive rubber adhesive for strong bond', 'Resistant to abrasion, moisture, and wear'], uses: ['Marking physical hazards', 'Aisle marking in warehouses', 'Indicating safety equipment locations', 'Construction site warnings'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/hazardtape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'floor-marking-tape', name: 'Heavy-Duty Floor Marking Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/floor%20marking%20tape.webp', shortDescription: 'Designed for long-term industrial use, this floor marking tape withstands forklift pressure, cleaning machines, and continuous foot traffic. The reinforced PVC layer prevents peeling, curling, and fading. Ideal for marking aisles, storage sections, workstations, and production lanes. Provides a cleaner alternative to painted floors.', category: 'safety-tapes', features: ['Tough vinyl backing resists heavy traffic', 'Available in multiple solid colors', 'Removes cleanly without residue', 'Easy to apply'], uses: ['Warehouse aisle marking', 'Designating work cells', 'Social distancing markers', 'Safety equipment zones'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/floor%20marking%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'coloured-anti-slip-tape', name: 'Heavy-Duty Anti-Skid & Anti-Slip Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/coloured-anti-slip-tape.webp', shortDescription: 'This anti-slip tape features a high-grit mineral coating for strong traction in wet or oily industrial environments. Commonly used on platforms, ramps, stairs, and moving machinery zones. It withstands chemicals, heavy loads, and outdoor exposure. A reliable safety solution for factories, workshops, and logistic facilities.', category: 'safety-tapes', features: ['High-traction mineral-coated surface', 'Durable and long-lasting adhesive', 'Water and chemical resistant', 'Suitable for indoor and outdoor use'], uses: ['Stairs and steps', 'Ramps and walkways', 'Loading docks', 'Wet floor areas'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/coloured-anti-slip-tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'caution-tape', name: 'Non-Adhesive Caution & Warning Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/caution%20tape.webp', shortDescription: 'This tear-resistant polyethylene tape is used to cordon off hazard zones, construction sites, and maintenance areas. Its bold printed messaging provides clear warnings from long distances. Lightweight, reusable, and easy to deploy on barricades, poles, and cones. Suitable for both indoor and outdoor safety marking.', category: 'safety-tapes', features: ['Bright, fade-resistant colors', 'Durable polyethylene construction', 'Weatherproof and tear-resistant', 'Lightweight and easy to use'], uses: ['Construction sites', 'Hazardous material spills', 'Crime scenes', 'Event crowd control'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/caution%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'barricade-tape', name: 'Non-Adhesive Barricade Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/barricade%20tape.webp', shortDescription: 'A durable and weather-resistant barricade tape used for temporarily blocking restricted areas. Ideal for road work, events, industrial maintenance, and emergencies. The non-adhesive design allows quick installation and reuse. Offers high visibility for crowd control and hazard indication.', category: 'safety-tapes', features: ['High visibility', 'Tear-resistant polyethylene', 'Non-adhesive for easy removal'], uses: ['Crowd control', 'Construction sites', 'Law enforcement'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/barricade%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'tamper-proof-tape-1', name: 'Tamper-Proof Security Packing Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/tamper-proof-tape-1.webp', shortDescription: 'Security tape reveals “VOID” or tamper-evident marks if removed or cut, making it essential for high-value industrial shipments. It prevents unauthorized access during logistics and warehousing. Resistant to heat, solvents, and peeling attempts. Used in electronics, pharmaceuticals, and confidential shipments.', category: 'safety-tapes', features: ['Provides visual evidence of tampering', 'Strong polyester backing', 'Aggressive adhesive for secure sealing'], uses: ['Sealing high-value goods', 'Pharmaceutical packaging', 'Electronics shipping'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/tamper-proof-tape-1.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'nastro-heavy-duty-floor-marking', name: 'Nastro Heavy Duty Floor Marking Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/nastro%20heavy%20duty%20floor%20marking.webp', shortDescription: 'This premium floor marking tape withstands heavy forklift activity and continuous industrial operations. The robust PVC backing resists tearing and maintains color vibrancy. Ideal for zoning, safety lanes, and workflow planning. Ensures long-term clarity and reliability in manufacturing plants.', category: 'safety-tapes', features: ['Laminated for extreme durability', 'Resists forklifts and heavy machinery', 'Beveled edges to prevent lifting'], uses: ['Heavy industrial warehouses', 'Manufacturing facilities', 'Logistics centers'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/nastro%20heavy%20duty%20floor%20marking.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'glowindark', name: 'Glow in the Dark Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/glowindark.webp', shortDescription: 'Glow Tape absorbs light and emits a bright glow during power failure or low-light conditions. Used for emergency exits, stair edges, and evacuation pathways. Non-toxic, durable, and ideal for industrial safety routes. Enhances visibility during nighttime or blackouts.', category: 'safety-tapes', features: ['High-intensity glow', 'Charges quickly from any light source', 'Durable vinyl construction'], uses: ['Marking escape routes', 'Stairways and handrails', 'Light switch surrounds'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/glowindark.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'photoluminescent-film', name: 'Photoluminescent Film', image: 'https://file.garden/aIULwzQ_QkPKQcGw/Photoluminescent%20Film.webp', shortDescription: 'This glow film is used for safety signs, floor arrows, and emergency maps. It charges under normal light and glows brightly in darkness. Resistant to moisture and chemicals, making it reliable in industrial spaces. Essential for evacuation planning in manufacturing units.', category: 'safety-tapes', features: ['Long-lasting glow properties', 'Available in adhesive and rigid forms', 'Meets safety regulations'], uses: ['Exit signs', 'Fire safety signage', 'Marine safety applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/Photoluminescent%20Film.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'anti-skid-glow-in-dark', name: 'Anti-Skid Tape with Centre Glow', image: 'https://file.garden/aIULwzQ_QkPKQcGw/anti%20skid%20glow%20in%20dark.webp', shortDescription: 'A dual-function tape combining anti-slip traction with a glowing center strip. Perfect for stairs, platforms, and walkways where both grip and visibility are required. Enhances nighttime safety and prevents slips in dark industrial zones.', category: 'safety-tapes', features: ['Dual-purpose safety', 'Mineral-coated anti-slip surface', 'Bright glow-in-the-dark center line'], uses: ['Emergency exit stairs', 'Dark corridors and walkways', 'Industrial platforms'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/anti%20skid%20glow%20in%20dark.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'esd-floor-marking', name: 'ESD Floor Marking Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/esd%20floor%20marking.webp', shortDescription: 'Designed for electrostatic-protected areas, this tape prevents static buildup and helps identify ESD-safe zones. Used in electronics manufacturing, PCB labs, and cleanrooms. Strong adhesive ensures long-term durability even in controlled environments.', category: 'safety-tapes', features: ['Low static-generating properties', 'Clear ESD symbol printed', 'Durable for foot traffic'], uses: ['Defining EPA boundaries', 'Marking walkways in electronics labs', 'Cleanroom applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/esd%20floor%20marking.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'glowindark-marking', name: 'Glow in Dark Marking Tapes', image: 'https://file.garden/aIULwzQ_QkPKQcGw/glowindark%20marking.webp', shortDescription: 'This marking tape glows brightly after light exposure, guiding workers during low-light situations. Ideal for marking hazardous edges, machine outlines, and evacuation paths. Long-lasting glow and high visibility enhance industrial safety workflows.', category: 'safety-tapes', features: ['Available in various widths', 'Easy to apply', 'Long-lasting afterglow'], uses: ['Directional marking', 'Stage and theater marking', 'Home safety'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/glowindark%20marking.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'anti-skid', name: 'Heavy Duty Anti-Skid Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/anti%20skid.webp', shortDescription: 'A high-friction industrial tape built to withstand heavy machinery movement and chemical exposure. Ideal for ramps, oily floors, ladders, and safety-critical areas. Ensures worker stability and reduces fall accidents in demanding environments.', category: 'safety-tapes', features: ['Extra-coarse abrasive surface', 'Resists oil, water, and heavy wear', 'Aggressive adhesive for rough surfaces'], uses: ['Offshore oil rigs', 'Manufacturing plants', 'Construction vehicles'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/anti%20skid.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'anti-slip-bathroom', name: 'Anti-Slip Tape for Bath and Shower', image: 'https://file.garden/aIULwzQ_QkPKQcGw/anti%20slip%20bathroom.webp', shortDescription: 'A waterproof anti-slip tape designed for wet, barefoot environments. Provides gentle but firm grip on smooth wet tiles. Ideal for dormitories, industrial restrooms, pools, and worker hygiene areas. Durable and skin-friendly.', category: 'safety-tapes', features: ['Waterproof and mold-resistant', 'Soft-textured, non-abrasive surface', 'Clear design blends with decor'], uses: ['Bathtubs and shower floors', 'Around swimming pools', 'Locker rooms'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/anti%20slip%20bathroom.webp'] },

    // --- Reflective Tapes ---
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'silver-tc', name: 'Silver TC Sew-On Reflective Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/silver%20tc.webp', shortDescription: 'This TC-based sew-on tape reflects light powerfully, improving visibility for workers at night or in low-light conditions. Used in safety jackets, uniforms, and industrial PPE. Withstands repeated washing and rough usage.', category: 'reflective-tapes', features: ['High reflectivity (EN 20471 compliant)', 'Durable TC (Terylene/Cotton) backing', 'Washable and long-lasting', 'Easy to sew'], uses: ['Safety vests', 'Work jackets and pants', 'Firefighter uniforms', 'Jogging and cycling gear'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/silver%20tc.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'heattransfer', name: 'Heat Transfer Reflective Film', image: 'https://file.garden/aIULwzQ_QkPKQcGw/heattransfer.webp', shortDescription: 'A heat-pressed reflective film used in high-visibility uniforms and safety clothing. Bonds strongly to fabric and maintains reflectivity after washing. Ideal for industrial PPE manufacturers and corporate uniform branding.', category: 'reflective-tapes', features: ['Applies with heat press or iron', 'Excellent reflectivity', 'Durable through washing'], uses: ['T-shirts and sportswear', 'Work uniforms', 'Caps and bags'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/heattransfer.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'heat-transfer-reflective-vinyl-film-tape-heat-transfer-segmented-reflective-tape', name: 'Vinyl Heat Transfer Reflective Film', image: 'https://file.garden/aIULwzQ_QkPKQcGw/Heat-Transfer-Reflective-Vinyl-Film-Tape-Heat-Transfer-Segmented-Reflective-Tape.webp', shortDescription: 'Soft, flexible reflective vinyl ideal for heat transfers onto fabrics. Provides exceptional retro-reflection and comfort. Used for logos, stripes, and markings on uniforms for factories, warehouses, and road workers.', category: 'reflective-tapes', features: ['Stretchable and flexible', 'Easy to weed and apply', 'Bright reflective finish'], uses: ['Custom logos on sportswear', 'Athletic apparel', 'Fashion garments'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/Heat-Transfer-Reflective-Vinyl-Film-Tape-Heat-Transfer-Segmented-Reflective-Tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'pvc-reflective-tape', name: 'PVC Reflective Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/pvc%20reflective%20tape.webp', shortDescription: 'A durable reflective tape used for marking vehicles, machinery, and equipment. Its micro-prismatic surface ensures high visibility from long distances. Weather-resistant and suitable for outdoor industrial applications.', category: 'reflective-tapes', features: ['Microprismatic technology for high brightness', 'Weather and solvent resistant', 'Strong adhesive backing'], uses: ['Trucks and trailers', 'Roadside signs', 'Bollards and barriers'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/pvc%20reflective%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'grey-reflective-yarn-2-0-mm-double-side-500x500-1', name: 'Reflective Yarn & Thread', image: 'https://file.garden/aIULwzQ_QkPKQcGw/grey-reflective-yarn-2-0-mm-double-side-500x500%20(1).webp', shortDescription: 'Woven directly into fabrics, this reflective yarn enhances visibility of uniforms, bags, and PPE. Provides brightness under headlights or torchlight. Used in industrial safety apparel manufacturing.', category: 'reflective-tapes', features: ['Can be woven or sewn', 'Provides 360-degree reflectivity', 'Soft and flexible'], uses: ['Sportswear', 'Shoelaces', 'Hats and gloves'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/grey-reflective-yarn-2-0-mm-double-side-500x500%20(1).webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'material-fr-reflective-tape-all-1', name: 'Flame Retardant Reflective Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/material-fr-reflective-tape-all%20(1).webp', shortDescription: 'Designed for high-heat environments like welding, firefighting, and foundry work. Offers strong reflectivity even under extreme heat exposure. Sewn into protective clothing and flame-resistant gear.', category: 'reflective-tapes', features: ['Meets flame retardant standards (e.g., NFPA)', 'Aramid fiber backing', 'High heat resistance'], uses: ['Firefighter turnout gear', 'Welding apparel', 'Oil and gas industry workwear'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/material-fr-reflective-tape-all%20(1).webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'high-reflective-polyester', name: 'Hi-Reflective Polyester Fabric', image: 'https://file.garden/aIULwzQ_QkPKQcGw/high%20reflective%20polyester.webp', shortDescription: 'A reflective polyester fabric used for safety vests and industrial uniforms. Lightweight, washable, and highly visible. Ideal for PPE manufacturing and workwear production.', category: 'reflective-tapes', features: ['Bright fluorescent colors', 'Durable polyester material', 'Used as base fabric for safety wear'], uses: ['Safety vests', 'High-visibility jackets', 'Bags and accessories'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/high%20reflective%20polyester.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'hipoloyster', name: 'Hi-Reflective TC Fabric', image: 'https://file.garden/aIULwzQ_QkPKQcGw/hipoloyster.webp', shortDescription: 'A polyester-cotton blend that provides comfort plus strong reflective performance. Used for jackets, coveralls, and visibility garments. Maintains brightness after repeated industrial washing.', category: 'reflective-tapes', features: ['Breathable and strong TC blend', 'Fluorescent for daytime visibility', 'Ideal base for work uniforms'], uses: ['Work shirts and pants', 'Boiler suits', 'Durable safety garments'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/hipoloyster.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'oxfordrefle', name: 'Oxford Reflective Ribbon', image: 'https://file.garden/aIULwzQ_QkPKQcGw/oxfordrefle.webp', shortDescription: 'A durable ribbon that adds reflective detailing to industrial uniforms, bags, and accessories. Strong woven structure resists fraying and wear. Enhances night visibility on PPE.', category: 'reflective-tapes', features: ['Strong Oxford fabric base', 'Central reflective stripe', 'Ideal for trimming and reinforcement'], uses: ['Trims on jackets and bags', 'Reinforcing seams on workwear', 'Pet accessories'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/oxfordrefle.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'grey-reflective-piping', name: 'Reflective Piping', image: 'https://file.garden/aIULwzQ_QkPKQcGw/grey-reflective-piping.webp', shortDescription: 'Reflective piping is sewn along garment edges to improve low-light visibility. Common in jackets, rainwear, bags, and safety uniforms. Flexible and durable for industrial usage.', category: 'reflective-tapes', features: ['Adds reflective accents to seams', 'Flexible and easy to sew', 'Enhances product design'], uses: ['Athletic wear', 'Jackets and vests', 'Backpacks'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/grey-reflective-piping.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'ordinary-polyster-fabric', name: 'Ordinary Reflective Polyester Fabric', image: 'https://file.garden/aIULwzQ_QkPKQcGw/ordinary%20polyster%20fabric.webp', shortDescription: 'An economical reflective fabric option for mass-produced safety gear. Suitable for belts, vests, and general-purpose visibility accessories. Provides steady reflectivity at low cost.', category: 'reflective-tapes', features: ['Economical choice', 'Good reflectivity', '100% polyester'], uses: ['Promotional items', 'Costumes', 'Casual wear'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/ordinary%20polyster%20fabric.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'woven', name: 'Woven Reflective Ribbon', image: 'https://file.garden/aIULwzQ_QkPKQcGw/Gemini_Generated_Image_lutclolutclolutc.webp.', shortDescription: 'A glass-bead enhanced reflective ribbon used in uniforms, caps, and safety gear. Durable construction provides strong retro-reflection. Ideal for industrial garment stitching.', category: 'reflective-tapes', features: ['Integrated reflectivity', 'Soft and flexible', 'High-end appearance'], uses: ['Branded apparel', 'Lanyards', 'Fashion accents'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/Gemini_Generated_Image_lutclolutclolutc.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'ordinary-reflective-tc-fabric', name: 'Ordinary Reflective TC Fabric', image: 'https://file.garden/aIULwzQ_QkPKQcGw/silver%20tc.webp', shortDescription: 'A cost-effective TC fabric for basic reflective clothing. Used in entry-level safety jackets, belts, and accessories. Provides dependable reflectivity and wash durability.', category: 'reflective-tapes', features: ['Good balance of cost and performance', 'Durable TC blend', 'Suitable for general workwear'], uses: ['General purpose safety vests', 'Utility worker uniforms', 'Event staff apparel'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/silver%20tc.webp'] },

    // --- Double Sided Tapes ---
// FIX: Add required 'image' property to satisfy the Product type.
    { id: '3m-foam-foam-tape', name: '3M Double-Sided Foam Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/3M%20Foam%20Tape%20with%20Liner.webp', shortDescription: 'A premium bonding tape distributed by Tape India, used in automotive trims, electronics, and signage. Absorbs vibration and bonds uneven surfaces. Provides long-lasting adhesion even under thermal stress.', category: 'double-sided-tapes', features: ['Conformable acrylic foam core', 'High shear strength', 'Resists weathering and moisture'], uses: ['Automotive emblems and trim', 'Signage and display mounting', 'Panel bonding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/3M%20Foam%20Tape%20with%20Liner.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'tissue-tape', name: 'Double-Sided Tissue Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/tissue%20tape.webp', shortDescription: 'A thin, flexible tape ideal for laminating paper, film, and textiles. Used in printing, packaging, and garment manufacturing. Provides strong bonding without bulk.', category: 'double-sided-tapes', features: ['Hand-tearable', 'Good adhesion to various surfaces', 'Available with rubber or acrylic adhesive'], uses: ['Splicing paper and films', 'Mounting lightweight objects', 'Crafts and office use'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/tissue%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'polyester-double-side', name: 'Polyester Double Sided Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/polyester%20double%20side.webp', shortDescription: 'PET-based double-sided tape with excellent tensile strength and heat resistance. Ideal for splicing, electrical insulation, and industrial lamination processes.', category: 'double-sided-tapes', features: ['High tensile strength', 'Dimensionally stable', 'Good temperature resistance'], uses: ['Laminating foams and fabrics', 'Mounting nameplates', 'Splicing films'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/polyester%20double%20side.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'vhb-tape', name: 'VHB (Very High Bond) Double-Sided Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/vhb%20tape.webp', shortDescription: 'A high-strength acrylic foam tape that replaces welding, screws, and rivets. Used for metal, glass, and composite bonding in automotive, signage, and electronics assembly.', category: 'double-sided-tapes', features: ['Extremely strong viscoelastic acrylic foam', 'Creates a permanent, durable seal', 'Resistant to temperature extremes, UV, and moisture', 'Absorbs shock and vibration'], uses: ['Panel to frame bonding', 'Automotive trim attachment', 'Architectural signage mounting', 'Electronics assembly'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/vhb%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'lohmann', name: 'Lohmann DuploFLEX Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/lohman.webp', shortDescription: 'A specialized flexographic printing mounting tape. Provides even pressure distribution and easy plate mounting/demounting. Used in high-speed printing lines for consistent output.', category: 'double-sided-tapes', features: ['Optimized foam density', 'Excellent print quality', 'Clean removal from plate and cylinder'], uses: ['Mounting photopolymer plates', 'Flexographic printing presses', 'Label and packaging printing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/lohman.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'pe-foam-tape', name: 'PE Foam Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/pe%20foam%20tape.webp', shortDescription: 'PE foam tape provides cushioning, sealing, and vibration damping. Used in HVAC insulation, automotive assembly, and glass-to-metal joints. Strong moisture resistance ensures long-life performance.', category: 'double-sided-tapes', features: ['Good gap-filling properties', 'Seals against dust and moisture', 'Available in various thicknesses'], uses: ['Mirror mounting', 'Gasketing applications', 'Sound dampening'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/pe%20foam%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'pet-double-sided-tape', name: 'PET Double-Sided Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/pet%20double%20sided%20tape.webp', shortDescription: 'High-strength adhesive tape ideal for splicing films, bonding nameplates, and electronic components. Its PET base offers excellent stability under mechanical stress.', category: 'double-sided-tapes', features: ['Optically clear', 'High initial tack', 'Resistant to plasticizers'], uses: ['Mounting POS displays', 'Laminating transparent materials', 'Electronics assembly'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/pet%20double%20sided%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'transfer-tape', name: 'Transfer Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/transfer%20tape.webp', shortDescription: 'A carrier-less adhesive layer used in precision lamination for electronics, overlays, and nameplates. Transparent, heat-resistant, and ideal for die-cutting operations.', category: 'double-sided-tapes', features: ['Unsupported adhesive film', 'Highly conformable', 'Available in various thicknesses'], uses: ['Graphic attachment', 'Laminating nameplates', 'Bonding gaskets'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/transfer%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'acrylic-double-sided-tape-1', name: 'Acrylic Double Sided Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/Acrylic%20Double%20Sided%20Tape%20(1).webp', shortDescription: 'Clear acrylic tape with superior adhesion to metals, plastics, and glass. UV and weather-resistant, making it ideal for outdoor industrial bonding. Used in signage, appliances, and automotive components.', category: 'double-sided-tapes', features: ['Transparent and durable', 'Excellent UV and temperature resistance', 'Creates a virtually invisible bond'], uses: ['Glass bonding', 'Architectural panel mounting', 'Automotive applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/Acrylic%20Double%20Sided%20Tape%20(1).webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'double-sided-thermal-tape', name: 'Double-Sided Thermal Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/double%20sided%20thermal%20tape.webp', shortDescription: 'Thermally conductive tape for heat sinks, ICs, LEDs, and power modules. Provides heat dissipation while maintaining electrical insulation. Essential in electronics assembly.', category: 'double-sided-tapes', features: ['Excellent thermal conductivity', 'Good dielectric strength', 'Provides both bond and heat transfer'], uses: ['Mounting heat sinks on CPUs and GPUs', 'LED lighting applications', 'Power transistors'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/double%20sided%20thermal%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'double-sided-scrim-tape', name: 'Double-Sided Scrim Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/Double-Sided%20Scrim%20Tape.webp', shortDescription: 'Reinforced scrim mesh gives this tape superior shear strength. Used for carpet installation, insulation joints, and construction bonding. Works well on rough or dusty surfaces.', category: 'double-sided-tapes', features: ['Fiberglass reinforcement prevents stretching', 'High shear strength', 'Aggressive adhesive'], uses: ['Carpet and vinyl flooring installation', 'Insulation panel mounting', 'Splicing heavy materials'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/Double-Sided%20Scrim%20Tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'eva-foam-tape', name: 'EVA Foam Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/eva%20foam%20tape.webp', shortDescription: 'EVA foam tape provides shock absorption, sealing, and cushioning. Used in HVAC, automotive interiors, appliances, and fabrication. Resistant to UV and chemicals.', category: 'double-sided-tapes', features: ['Cost-effective solution', 'Good cushioning and sealing properties', 'Adheres to a variety of surfaces'], uses: ['Lightweight mounting', 'Weatherstripping', 'Dust sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/eva%20foam%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'spacer-tape', name: 'Spacer Tapes', image: 'https://file.garden/aIULwzQ_QkPKQcGw/spacer%20tape.webp', shortDescription: 'Used in structural glazing to maintain even spacing during sealant curing. Open-cell foam allows proper airflow. Essential for façade and curtain wall systems.', category: 'double-sided-tapes', features: ['Open-cell polyurethane or PVC foam', 'Compatible with structural silicones', 'Ensures correct sealant depth'], uses: ['Structural silicone glazing', 'Curtain wall systems', 'Window manufacturing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/spacer%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'silicone-tape', name: 'Nano Magic Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/silicone%20tape.webp', shortDescription: 'Reusable, washable gel tape that sticks to most smooth surfaces. Used for prototype mounting, temporary setups, and lab/assembly line fixtures. Leaves no residue.', category: 'double-sided-tapes', features: ['Washable and reusable', 'Strong adhesion', 'Leaves no residue'], uses: ['Temporary mounting of pictures', 'Holding down rugs', 'Organizing cables'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/silicone%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'hot-melt-tissue-tape', name: 'Hot Melt Tissue Tapes', image: 'https://file.garden/aIULwzQ_QkPKQcGw/hot%20melt%20tissue%20tape.webp', shortDescription: 'High-tack double-sided tissue tape used in foam, leather, and textile bonding. Instant adhesion makes it suitable for high-speed industrial production.', category: 'double-sided-tapes', features: ['Very high initial tack', 'Excellent adhesion to rough surfaces', 'Good for bonding plastics like PE and PP'], uses: ['Bag sealing', 'Mounting plastic trims', 'Splicing corrugated materials'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/hot%20melt%20tissue%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'double-coated-cloth-tape-581', name: 'Double Sided Cloth Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/double-coated-cloth-tape-581.webp', shortDescription: 'Strong cloth backing provides durability on rough surfaces. Used for carpet laying, event setups, and industrial bundling. Easy to tear by hand yet strong.', category: 'double-sided-tapes', features: ['Strong cloth carrier', 'High adhesion and shear strength', 'Conformable to irregular surfaces'], uses: ['Carpet and flooring installation', 'Temporary event flooring', 'Stereo mounting in printing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/double-coated-cloth-tape-581.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'aacrylic-gel-tape-1', name: 'Acrylic Gel Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/aAcrylic%20Gel%20Tape%20(1).webp', shortDescription: 'Extremely strong transparent gel tape for permanent bonding. Used in architectural panels, signage, and metal-to-glass assembly. Absorbs vibration and distributes load.', category: 'double-sided-tapes', features: ['Optically clear', 'Waterproof and weatherproof', 'Replaces screws, rivets, and welds'], uses: ['Mounting signs and displays', 'Automotive trim', 'Glass and transparent plastic bonding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/aAcrylic%20Gel%20Tape%20(1).webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'xlpe-foam-tapes', name: 'XLPE Foam Tapes', image: 'https://file.garden/aIULwzQ_QkPKQcGw/XLPE-FOAM-TAPES.webp', shortDescription: 'Cross-linked polyethylene foam tape used for sealing, soundproofing, and cushioning. Excellent moisture resistance makes it suitable for outdoor industrial use.', category: 'double-sided-tapes', features: ['Closed-cell structure', 'Good thermal and acoustic insulation', 'Chemical and moisture resistant'], uses: ['HVAC gasketing', 'Appliance manufacturing', 'Window glazing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/XLPE-FOAM-TAPES.webp'] },

    // --- Specialty Tapes ---
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'masking-tape', name: 'Masking Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/masking%20tape.webp', shortDescription: 'Industrial-grade masking tape for clean paint lines and high-temperature masking. Used in automotive refinishing, powder coating, and general maintenance.', category: 'specialty-tapes', features: ['Crepe paper backing', 'Removes cleanly', 'Easy to tear'], uses: ['Painting and decorating', 'Bundling light items', 'Labeling'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/masking%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'bopp-tape', name: 'BOPP Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/bopp%20tape.webp', shortDescription: 'Strong carton-sealing tape used in packaging lines, logistics, and warehousing. High tensile strength and long-lasting adhesion ensure secure packaging.', category: 'specialty-tapes', features: ['Strong polypropylene backing', 'Available in clear, brown, and custom prints', 'Water-based acrylic adhesive'], uses: ['Carton and box sealing', 'Packaging and shipping', 'Bundling'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/bopp%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'aluminum-foil-2-tape', name: 'High-Performance Aluminium Foil Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/aluminum%20foil%20%202%20tape.webp', shortDescription: 'Used in HVAC, insulation, and EMI shielding. Reflects heat and seals moisture barriers. Strong adhesive bonds even on cold surfaces.', category: 'specialty-tapes', features: ['Thermally conductive', 'Reflects heat and light', 'Resists moisture, UV, and chemicals'], uses: ['Duct sealing in HVAC systems', 'EMI/RFI shielding', 'Heat shielding applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/aluminum%20foil%20%202%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'kapton-tape', name: 'High-Temperature Kapton Polyimide Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/kapton%20tape.webp', shortDescription: 'Withstands up to 260°C, ideal for PCB solder masking, battery insulation, and aerospace components. Leaves minimal residue after heat exposure.', category: 'specialty-tapes', features: ['Withstands extreme temperatures (up to 260°C)', 'Excellent dielectric strength', 'Removes cleanly'], uses: ['Masking for circuit boards during wave soldering', 'Electrical insulation', '3D printing bed surface'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/kapton%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'duct-tape', name: 'Heavy-Duty Cloth Duct Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/duct%20tape.webp', shortDescription: 'Reinforced cloth duct tape for repairs, sealing, and bundling. Bonds to concrete, metal, and wood. Water-resistant and ideal for industrial maintenance.', category: 'specialty-tapes', features: ['Waterproof PE-coated cloth backing', 'Strong rubber-based adhesive', 'Hand-tearable'], uses: ['General repairs', 'Duct and pipe sealing', 'Heavy-duty bundling'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/duct%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'high-sealing-tape', name: 'High Temperature Sealing Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/high%20sealing%20tape.webp', shortDescription: 'A specialized tape designed for sealing oven doors, furnace insulation, and high-temperature ducts. Resistant to chemicals, abrasion, and thermal cycling. Maintains bond integrity even at extreme heat levels. Used in metal processing, heat treatment plants, and industrial manufacturing lines.', category: 'specialty-tapes', features: ['Various material compositions (e.g., fiberglass, silicone)', 'Maintains seal integrity at high temps', 'Chemical resistant'], uses: ['Industrial ovens', 'Engine compartments', 'Exhaust systems'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/high%20sealing%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'paper-tape', name: 'Paper Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/kraft%20tape.webp', shortDescription: 'Eco-friendly kraft-based tape suitable for carton sealing, splicing paper rolls, and packaging. Bonds firmly with pressure and is fully recyclable. Ideal for sustainable factories, printing houses, and packaging lines. Printable for branding or handling information.', category: 'specialty-tapes', features: ['Kraft paper backing', 'Recyclable and biodegradable', 'Good adhesion'], uses: ['Picture framing', 'Packaging', 'Craft projects'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/kraft%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'silicone-tape-2', name: 'Silicone Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/silicone%20tape%202.webp', shortDescription: 'Self-fusing silicone tape creates airtight and waterproof seals without adhesive. Used for emergency electrical insulation, pipe repair, and high-temperature applications. Highly flexible and resistant to UV, chemicals, and heat. Essential for power plants, marine, and aerospace maintenance.', category: 'specialty-tapes', features: ['Self-fusing (bonds to itself)', 'Waterproof and airtight', 'High temperature and UV resistance'], uses: ['Leaking pipe repairs', 'Electrical wire insulation', 'Hose and cable wrapping'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/silicone%20tape%202.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'polyester-tape', name: 'Single-sided polyester tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/yellow%20polyester.webp', shortDescription: 'A high-dielectric tape used in motors, transformers, capacitors, and coil wrapping. Polyester film offers stability under thermal stress. Also used for high-temperature powder coating masking. Provides excellent insulation and long-term reliability in electrical systems.', category: 'specialty-tapes', features: ['High tensile strength', 'Chemical and temperature resistant', 'Available in various colors'], uses: ['Splicing films and papers', 'Powder coating masking', 'Electrical insulation'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/yellow%20polyester.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'pvc-pipe-tape-1', name: 'PVC Pipe Wrapping Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/pvc%20pipe%20tape%20(1).webp', shortDescription: 'Designed for corrosion protection of pipelines, this tape resists moisture, chemicals, and abrasion. Used for underground and above-ground metal pipes to extend service life. Flexible and easy to apply for contractors and industrial maintenance teams. Ensures long-term protection in harsh conditions.', category: 'specialty-tapes', features: ['Protects against corrosion and abrasion', 'Flexible and conformable', 'Moisture and chemical resistant'], uses: ['Wrapping metal pipes and conduits', 'Underground pipeline protection', 'Joint and fitting sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/pvc%20pipe%20tape%20(1).webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'bag-sealing-tape', name: 'Bag Sealing Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/bag%20sealing%20tape.webp', shortDescription: 'Tape used in high-speed packaging lines for sealing polybags. Offers smooth release and clean closure. Available in permanent and resealable versions for manufacturing and retail packaging. Widely used in garment, FMCG, and electronics industries.', category: 'specialty-tapes', features: ['Quick and easy to apply', 'Provides a secure seal', 'Available in various colors for coding'], uses: ['Bakery and produce bags', 'Retail packaging', 'Industrial bag sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/bag%20sealing%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'acetate-cloth-tape-white-19mm-x-66m-crop', name: 'Acetate Cloth Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/acetate-cloth-tape-white-19mm-x-66m-crop.webp', shortDescription: 'A flexible cloth tape used for coil winding and wire harnessing in transformers and motors. Offers heat resistance, good insulation, and strong adhesion. Easy to unwind and apply uniformly. Trusted in electrical assembly and OEM manufacturing.', category: 'specialty-tapes', features: ['Excellent conformability', 'Good electrical insulation properties', 'Printable surface'], uses: ['Coil and transformer wrapping', 'Wire harnessing', 'Motor repairs'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/acetate-cloth-tape-white-19mm-x-66m-crop.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'stickymat', name: 'Sticky Mat', image: 'https://file.garden/aIULwzQ_QkPKQcGw/stickymat.webp', shortDescription: 'A multi-layer dust-control mat placed at cleanroom entrances to capture dirt from shoes and trolley wheels. Each layer peels off when dirty, ensuring consistent hygiene. Used in pharmaceuticals, electronics, food processing, and labs. Reduces contamination and improves production quality.', category: 'specialty-tapes', features: ['Tacky surface removes contaminants', 'Peel-off sheets for a fresh surface', 'Non-skid backing'], uses: ['Cleanroom entrances', 'Hospitals and labs', 'Construction sites'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/stickymat.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'fine-line-masking-tape', name: 'Fine Line Masking Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/fine%20line%20masking%20tape.webp', shortDescription: 'Thin, flexible tape designed for sharp paint edges in automotive refinishing and industrial painting. Withstands high-temperature baking cycles. Adheres well to curves and contours without bleeding. A favorite in auto body shops and precision painting lines.', category: 'specialty-tapes', features: ['Creates sharp, precise paint lines', 'Flexible for curves and contours', 'Resists paint bleed-through'], uses: ['Automotive custom painting', 'Industrial painting', 'Graphic arts'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/fine%20line%20masking%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'mica-tape', name: 'Mica Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/mica%20tape.webp', shortDescription: 'Heat-resistant mica tape provides electrical insulation for high-temperature coils, cables, and heating devices. Does not burn or carbonize under prolonged heat. Used in motors, transformers, and furnace equipment. Excellent dielectric strength for extreme environments.', category: 'specialty-tapes', features: ['Excellent fire resistance', 'High dielectric strength', 'Flexible and easy to apply'], uses: ['Fire survival cables', 'Insulation for motors and generators', 'High-voltage applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/mica%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'green-polyster', name: 'Green Polyester Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/green%20polyester.webp', shortDescription: 'High-temperature green polyester tape widely used for powder coating, anodizing, and PCB masking. Silicone adhesive ensures clean removal even after heating. Common in finishing lines, electronics plants, and industrial surface protection.', category: 'specialty-tapes', features: ['Withstands high temperatures (up to 204°C)', 'Removes cleanly without residue', 'Chemical resistant'], uses: ['Powder coating masking', 'Anodizing and plating', 'Splicing silicone-coated papers'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/green%20polyester.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'green-polyster-with-liner', name: 'Green Polyester Tape with Liner', image: 'https://file.garden/aIULwzQ_QkPKQcGw/green%20polyster%20with%20liner.webp', shortDescription: 'A liner-backed version ideal for die-cutting into shapes for automated masking. Used in PCB manufacturing, powder coating fixtures, and precision masking operations. Offers excellent heat resistance and dimensional stability.', category: 'specialty-tapes', features: ['Release liner for easy die-cutting', 'Same high-temp performance', 'Precise masking shapes'], uses: ['Custom die-cut masking parts', 'Electronics masking', 'Aerospace applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/green%20polyster%20with%20liner.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'thermal-condu-pads', name: 'Thermal Conductive Pads', image: 'https://file.garden/aIULwzQ_QkPKQcGw/thermal%20condu%20pads.webp', shortDescription: 'Soft silicone-based pads used to transfer heat from electronic components to heat sinks. Offer strong insulation and thermal conductivity. Used in LED drivers, EV batteries, power converters, and industrial electronics. Easy to assemble, replacing messy thermal pastes.', category: 'specialty-tapes', features: ['High thermal conductivity', 'Gap-filling and vibration damping', 'Electrically isolating'], uses: ['Electronics cooling', 'LED lighting', 'Automotive electronics'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/thermal%20condu%20pads.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'surface-protection-tape', name: 'PE Surface Protection Film', image: 'https://file.garden/aIULwzQ_QkPKQcGw/surface%20protection%20tape.webp', shortDescription: 'A protective film applied to metal sheets, acrylic panels, glass, and laminates to prevent scratches during handling, fabrication, and transport. Removes cleanly without residue. Used in construction, kitchen appliance manufacturing, and aluminum composite panels.', category: 'specialty-tapes', features: ['Removes cleanly without residue', 'Available in various tack levels', 'Protects against abrasion and contamination'], uses: ['Protecting metal, plastic, and glass surfaces', 'Appliance manufacturing', 'Automotive component protection'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/surface%20protection%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'green-powder-coating-tape-500x500-1', name: 'Powder Coated Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/green-powder-coating-tape-500x500%20(1).webp', shortDescription: 'A specialized tape that withstands powder-coating ovens and high-bake temperatures. Provides crisp masking lines and adhesive stability. Used on hooks, jigs, metal parts, and fixtures during powder-coating processes. Essential for metal finishing industries.', category: 'specialty-tapes', features: ['High temperature resistance', 'Clean removal', 'Prevents paint ingress'], uses: ['Masking parts during powder coating', 'Masking threads and holes', 'High-temp finishing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/green-powder-coating-tape-500x500%20(1).webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'lamination-tape', name: 'Lamination Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/lamination%20tape.webp', shortDescription: 'Lamination tape ensures bubble-free adhesion in multilayer laminates, nameplates, and printed circuitry. Offers clarity, thermal stability, and consistent bonding. Used in electronics, branding, and identity plate manufacturing. Withstands heat and mechanical pressure during lamination.', category: 'specialty-tapes', features: ['Optically clear adhesive', 'Provides a protective layer', 'Bonds dissimilar materials'], uses: ['Graphic overlays', 'Laminating nameplates', 'Foam bonding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/lamination%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'foil-scrim-kraft-tape', name: 'Aluminium Foil Scrim Kraft Tape (FSK)', image: 'https://file.garden/aIULwzQ_QkPKQcGw/foil-scrim-kraft-tape.webp', shortDescription: 'A robust insulation tape combining aluminium foil, fiberglass scrim, and kraft paper. Excellent for sealing HVAC ducts, vapor barriers, and insulation joints. High tensile strength and flame resistance make it ideal for industrial insulation contractors.', category: 'specialty-tapes', features: ['Tri-directional reinforcement', 'High tensile strength', 'Acts as a vapor barrier'], uses: ['Sealing foil-faced insulation', 'HVAC duct wrapping', 'Vapor sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/foil-scrim-kraft-tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'aluminium-pet', name: 'Aluminium PET Tape (Alupet)', image: 'https://file.garden/aIULwzQ_QkPKQcGw/aluminium%20pet.webp', shortDescription: 'Combines aluminium’s reflectivity with polyester film’s durability. Used in EMI shielding, cable wrapping, HVAC ducts, and reflective insulation layers. Weather-resistant and dimensionally stable. Suitable for long-term industrial applications.', category: 'specialty-tapes', features: ['High tensile strength from PET layer', 'Heat and light reflective', 'Good for shielding'], uses: ['Cable shielding', 'Decorative applications', 'Heat shielding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/aluminium%20pet.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'butyl', name: 'Aluminium Butyl Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/butyl.webp', shortDescription: 'A waterproof sealing tape with butyl adhesive and aluminium backing. Bonds instantly to metal, concrete, and plastic. Ideal for roofing, gutters, windows, and automotive soundproofing. Provides permanent sealing against water, vibration, dust, and heat.', category: 'specialty-tapes', features: ['Excellent waterproofing', 'Strong adhesion to most surfaces', 'UV resistant'], uses: ['Roof and gutter repairs', 'Sealing joints in construction', 'Automotive sound deadening'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/butyl.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'fiberglass-tape', name: 'Fiber Glass Cloth Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/fiberglass%20tape.webp', shortDescription: 'High-strength fiberglass cloth tape used for thermal insulation, joint reinforcement, and electrical insulation. Withstands high temperatures and mechanical stress. Ideal for motors, transformers, and industrial furnaces. Provides long-lasting thermal protection.', category: 'specialty-tapes', features: ['High tensile strength', 'Abrasion resistant', 'Withstands high temperatures'], uses: ['High-temperature duct sealing', 'Reinforcing and repairing', 'Electrical insulation'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/fiberglass%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'nrm-foam-tape', name: 'NBR Foam Tapes', image: 'https://file.garden/aIULwzQ_QkPKQcGw/nrm%20foam%20tape.webp', shortDescription: 'Nitrile rubber foam tape offering great oil, fuel, and chemical resistance. Used in HVAC insulation, automotive gaskets, and equipment sealing. Strong closed-cell structure blocks moisture and air effectively. Flexible and durable under harsh industrial conditions.', category: 'specialty-tapes', features: ['Good resistance to oils and chemicals', 'Flexible and conformable', 'Excellent sealing properties'], uses: ['Gasketing and sealing', 'Cushioning and vibration damping', 'Automotive applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/nrm%20foam%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'air-vent-tape', name: 'Air Vent Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/air%20vent%20tape.webp', shortDescription: 'Used in automotive headlamps, electronics, and appliances to allow controlled ventilation while blocking dust and moisture. Prevents condensation and pressure buildup in sealed units. Long-lasting and weather-resistant.', category: 'specialty-tapes', features: ['Allows moisture vapor transmission', 'Prevents ingress of dust and water', 'Durable backing'], uses: ['Sealing polycarbonate multi-wall sheets', 'Venting electronic enclosures', 'Greenhouse construction'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/air%20vent%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'pink-rayon', name: 'Pink Rayon Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/pink%20rayon.webp', shortDescription: 'A smooth rayon tape used in coil winding, transformer insulation, and wire bundling. Offers good tensile strength and electrical insulation. Easy to apply for uniform coil binding. A staple in motor and transformer manufacturing.', category: 'specialty-tapes', features: ['High tensile strength', 'Low elongation', 'Printable surface'], uses: ['Coil wrapping and insulation', 'Banding and reinforcing', 'Printing industry applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/pink%20rayon.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'yellow-polyester', name: 'Yellow Polyester Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/yellow%20polyester.webp', shortDescription: 'A high-temperature polyester tape used for solder masking, electrical insulation, and powder coating lines. Provides clean removal and sharp masking for industrial finishing. Handles chemical and thermal exposure well.', category: 'specialty-tapes', features: ['Bright yellow color for visibility', 'Durable polyester backing', 'Good chemical resistance'], uses: ['Color-coding components', 'Splicing films', 'Decorative applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/yellow%20polyester.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'aluminium-fr-grade', name: 'Aluminium Glass Tape (FR Grade)', image: 'https://file.garden/aIULwzQ_QkPKQcGw/aluminium%20fr%20grade.webp', shortDescription: 'Flame-resistant aluminium glass cloth tape used in furnaces, welding areas, and high-heat cable wrapping. Reflects heat while offering insulation. Suitable for extreme temperature environments.', category: 'specialty-tapes', features: ['Fire retardant (FR grade)', 'High temperature resistance', 'Excellent strength and durability'], uses: ['Aerospace applications', 'Marine and shipbuilding', 'High-temp insulation sealing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/aluminium%20fr%20grade.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'red-pvc-non-adhesive-tape', name: 'PVC Pipe Wrapping Tape (Without Adhesive)', image: 'https://file.garden/aIULwzQ_QkPKQcGw/Red-PVC-Non-Adhesive-Tape.webp', shortDescription: 'A non-adhesive PVC wrap for spiral bundling of automotive wiring, pipes, and cables. Provides abrasion resistance and mechanical protection. Used in harnessing and electrical assemblies.', category: 'specialty-tapes', features: ['Non-adhesive, self-clinging under tension', 'Corrosion protection', 'Flexible and easy to apply'], uses: ['Wrapping underground pipes', 'Protecting tool handles', 'Color-coding pipes'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/Red-PVC-Non-Adhesive-Tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'glass-cloth-tape', name: 'Glass Cloth Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/glass%20cloth%20tape.webp', shortDescription: 'High-temperature glass cloth tape with strong adhesive for insulation and mechanical protection. Used in transformers, motors, and aerospace components. Resists heat, chemicals, and abrasion.', category: 'specialty-tapes', features: ['High temperature performance', 'Excellent tensile strength', 'Abrasion resistant'], uses: ['High-temp electrical insulation', 'Permanent sealing of high-temp ducts', 'Motor and transformer insulation'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/glass%20cloth%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'fr-grade-glass-cloth-tape', name: 'Glass Cloth Tape (FR Grade)', image: 'https://file.garden/aIULwzQ_QkPKQcGw/fr-grade-glass-cloth-tape.webp', shortDescription: 'A flame-retardant version designed for heavy-duty industrial environments. Suitable for high-voltage cable bundling, furnace wiring, and thermal insulation. Provides top-tier dielectric performance.', category: 'specialty-tapes', features: ['Meets flame retardancy specifications', 'High temperature insulation', 'Durable and abrasion resistant'], uses: ['Aerospace wire harnessing', 'Sealing in high-heat areas', 'Marine applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/fr-grade-glass-cloth-tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'filament-tape', name: 'Filament Tapes', image: 'https://file.garden/aIULwzQ_QkPKQcGw/filament%20tape.webp', shortDescription: 'Fiberglass-reinforced tape offering extremely high tensile strength. Used for bundling steel rods, securing heavy items, and palletizing. Resists tearing and is ideal for logistics and fabrication.', category: 'specialty-tapes', features: ['Extremely high tensile strength', 'Resistant to tears and abrasion', 'Available in single and bi-directional patterns'], uses: ['Palletizing and bundling heavy goods', 'Reinforcing shipping containers', 'Appliance component securing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/filament%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'ez-application-tape', name: 'EZ Application Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/ez-application-tape.webp', shortDescription: 'Designed for vinyl and graphic transfer, ensuring smooth, bubble-free application. Used by printers and signage manufacturers. Clear adhesive provides precise alignment for industrial decals.', category: 'specialty-tapes', features: ['Medium tack adhesive', 'Lays flat for easy application', 'Transparent for easy alignment'], uses: ['Sign making', 'Transferring vinyl decals', 'Graphic arts'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/ez-application-tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'kraft-paper-tape', name: 'Kraft Paper Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/kraft%20tape.webp', shortDescription: 'Environmentally friendly tape used for sealing boxes in industrial packing operations. Strong adhesion and recyclable quality make it suitable for export packaging. Printable for branding.', category: 'specialty-tapes', features: ['Eco-friendly paper backing', 'Strong adhesion', 'Can be written on'], uses: ['Light to medium duty carton sealing', 'Picture framing', 'Craft applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/kraft%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'reinforced-paper-tapes1', name: 'Reinforcement Kraft Paper Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/reinforced-paper-tapes1.webp', shortDescription: 'Fiberglass-reinforced kraft tape used for heavy-duty packaging and palletizing. High tear resistance and strong bonding make it ideal for industrial shipping. Tamper-evident and moisture-resistant.', category: 'specialty-tapes', features: ['Fiberglass reinforcement', 'High tensile strength', 'Water-activated or self-adhesive'], uses: ['Sealing heavy or over-stuffed cartons', 'Reinforcing boxes', 'High-security packaging'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/reinforced-paper-tapes1.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'water-activated-kraft-tape', name: 'Water Activated Kraft Paper Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/water%20activated%20kraft%20tape.webp', shortDescription: 'Forms a strong fiber-to-fiber bond with cartons once water is applied. Tamper-proof and ideal for international shipments. Eco-friendly alternative to plastic packaging tapes.', category: 'specialty-tapes', features: ['Forms a permanent bond with cardboard', 'Tamper-evident seal', 'Recyclable and eco-friendly'], uses: ['High-security shipping', 'Sealing corrugated boxes', 'Temperature-sensitive packaging'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/water%20activated%20kraft%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'cloth-adhesive-tape-500x500-1', name: 'Adhesive Cloth Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/cloth-adhesive-tape-500x500%20(1).webp', shortDescription: 'Strong cloth tape used for rough surfaces, bundling, stage setups, and industrial repairs. Bonds well to concrete, wood, and metal. Resistant to wear and easy to tear manually.', category: 'specialty-tapes', features: ['Durable cloth backing', 'Available in multiple colors', 'Conformable and easy to tear'], uses: ['Bookbinding and spine repairs', 'Color-coding cables', 'General purpose repairs'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/cloth-adhesive-tape-500x500%20(1).webp'] },

    // --- Teflon & PTFE Tapes ---
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'ptfe-coated-fabric-non-adhesive-1', name: 'Non-Adhesive PTFE Coated Fiberglass Fabric', image: 'https://file.garden/aIULwzQ_QkPKQcGw/ptef%20coated%20fabric%20non%20adhesive%20(1).webp', shortDescription: 'Heat-resistant PTFE-coated fabric used in conveyor belts, heat sealers, and composite molding. Non-stick surface withstands up to 260°C. Essential for high-temperature industrial machinery.', category: 'teflon-ptfe-tapes', features: ['Excellent non-stick properties', 'High temperature and chemical resistance', 'Durable and flexible'], uses: ['Heat sealing machine release sheets', 'Conveyor belting', 'Composite mold release'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/ptef%20coated%20fabric%20non%20adhesive%20(1).webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'ptfe-silicone-adhesive', name: 'PTFE (Teflon) Coated Tape with Silicone Adhesive', image: 'https://file.garden/aIULwzQ_QkPKQcGw/ptef%20silicone%20adhe.webp', shortDescription: 'High-temperature non-stick tape used in heat-sealing and packaging lines. Silicone adhesive withstands heat and removes cleanly. Prevents sticking, burning, and material buildup.', category: 'teflon-ptfe-tapes', features: ['Non-stick PTFE surface', 'High-temperature silicone adhesive', 'Excellent chemical resistance'], uses: ['Heat sealer bar covering', 'Mold release liners', 'Chute and hopper linings'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/ptef%20silicone%20adhe.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'ptfe-fiberglass-with-silicone-adhesive', name: 'PTFE Coated Fiberglass Fabric with Silicone Adhesive', image: 'https://file.garden/aIULwzQ_QkPKQcGw/ptef%20fiberglass%20with%20silicone%20adhesive.webp', shortDescription: 'Reinforced fiberglass fabric coated with PTFE for heat resistance and durability. Used in insulation, sealing equipment, and industrial release surfaces.', category: 'teflon-ptfe-tapes', features: ['Heavy-duty PTFE coating', 'High-performance silicone adhesive', 'Longer lifespan in demanding applications'], uses: ['High-speed packaging machines', 'Demanding release applications', 'Industrial conveyor systems'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/ptef%20fiberglass%20with%20silicone%20adhesive.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'ptfe-coated-fiberglass-fabric-with-silicone-adhesive-liner', name: 'PTFE Coated Fiberglass Fabric with Liner', image: 'https://file.garden/aIULwzQ_QkPKQcGw/PTFE%20Coated%20Fiberglass%20Fabric%20with%20Silicone%20Adhesive%20%26%20Liner.webp', shortDescription: 'Includes a liner for die-cut shapes and precision placement. Ideal for heat-sealing jaws, lamination equipment, and non-stick machinery surfaces.', category: 'teflon-ptfe-tapes', features: ['Release liner for easy handling and die-cutting', 'Same high-temp, non-stick properties', 'Create custom gaskets and release surfaces'], uses: ['Die-cut non-stick parts', 'Custom release liners', 'Aerospace applications'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/PTFE%20Coated%20Fiberglass%20Fabric%20with%20Silicone%20Adhesive%20%26%20Liner.webp'] },

    // --- Antistatic & ESD Tapes ---
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'polyimide-tape', name: 'High-Temperature Kapton Polyimide Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/kapton%20tape.webp', shortDescription: 'Polyimide film tape offering excellent thermal stability at up to 260°C. Used in electronics, PCBs, sensors, EV batteries, and aerospace components.', category: 'antistatic-esd-tapes', features: ['Excellent thermal resistance (up to 260°C)', 'High dielectric strength', 'Clean removal'], uses: ['PCB masking during wave soldering', 'Electrical insulation of coils and motors', '3D printer beds'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/kapton%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'emi-sheliding-tape', name: 'EMI Shielding Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/emi%20sheliding%20tape.webp', shortDescription: 'Conductive tape designed to block electromagnetic interference in electronics. Essential for telecommunications, defense systems, and high-frequency devices.', category: 'antistatic-esd-tapes', features: ['Conductive adhesive', 'Provides effective EMI/RFI shielding', 'Flexible and conformable'], uses: ['Shielding cables and connectors', 'Grounding electronic components', 'Sealing EMI shielded rooms'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/emi%20sheliding%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'copper-tape-2', name: 'Conductive Copper Foil Tape for EMI Shielding', image: 'https://file.garden/aIULwzQ_QkPKQcGw/copper%20tape%202.webp', shortDescription: 'Pure copper foil tape with conductive adhesive for grounding and shielding. Used in PCBs, RF devices, audio equipment, and aerospace electronics.', category: 'antistatic-esd-tapes', features: ['Highly conductive copper foil', 'Conductive acrylic adhesive', 'Solderable'], uses: ['EMI shielding in electronics', 'Grounding applications', 'Stained glass crafting'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/copper%20tape%202.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'conductive-grind-tape', name: 'ESD Conductive Grid Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/conductive%20grind%20tape.webp', shortDescription: 'Anti-static tape used for sealing static-sensitive components and packaging. Prevents electrostatic discharge in cleanrooms and PCB manufacturing.', category: 'antistatic-esd-tapes', features: ['Creates a Faraday cage effect', 'Low static-generating', 'Transparent for visibility'], uses: ['Sealing ESD bags and containers', 'Use within EPAs', 'Securing documents in cleanrooms'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/conductive%20grind%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'esd-kapton', name: 'ESD Kapton Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/esd%20kapton.webp', shortDescription: 'Polyimide tape designed for static-safe environments. Combines heat resistance with anti-static properties. Used in soldering, PCBs, and semiconductor assembly.', category: 'antistatic-esd-tapes', features: ['High temperature resistance', 'Antistatic properties to prevent ESD events', 'Clean removal'], uses: ['Masking PCBs with static-sensitive components', 'High-temp applications in EPAs', 'Electronics assembly'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/esd%20kapton.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'anti-static-polyester-tape', name: 'Anti-Static Polyester Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/anti%20static%20polyester%20tape.webp', shortDescription: 'Transparent anti-static tape used in film processing, electronics assembly, and semiconductor work. Prevents static discharge and removes cleanly.', category: 'antistatic-esd-tapes', features: ['Reduces static generation', 'Durable polyester backing', 'Good for general purpose use in EPAs'], uses: ['Sealing and bundling in electronics assembly', 'Office use in EPAs', 'Labeling static-sensitive devices'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/anti%20static%20polyester%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'double-sided-polyimide-tapes-1', name: 'Polyimide Double-Sided Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/double-sided-polyimide-tapes-1.webp', shortDescription: 'A double-sided heat-resistant tape used for bonding electronic components, sensors, and EV battery layers. Offers strong adhesion under harsh temperatures.', category: 'antistatic-esd-tapes', features: ['Withstands high temperatures', 'Strong bonding on both sides', 'Dimensionally stable'], uses: ['Mounting components on PCBs before soldering', 'High-temp splicing', 'Aerospace bonding'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/double-sided-polyimide-tapes-1.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'polyimide-film-tape', name: 'Polyimide Film Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/polyimide%20flim%20tape.webp', shortDescription: 'Single-sided polyimide film tape for insulation, solder masking, and electrical protection. Ideal for high-temperature industrial and electronics applications.', category: 'antistatic-esd-tapes', features: ['High thermal and electrical insulation', 'Chemical resistant', 'Thin and conformable'], uses: ['General electrical insulation', 'Masking applications', 'Coil insulation'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/polyimide%20flim%20tape.webp'] },
// FIX: Add required 'image' property to satisfy the Product type.
    { id: 'tin-copper-tape', name: 'Tin-Plated Copper Tape', image: 'https://file.garden/aIULwzQ_QkPKQcGw/tin%20copper%20tape.webp', shortDescription: 'Tin-coated copper tape offers corrosion resistance and excellent conductivity. Used for EMI/RFI shielding, grounding straps, and high-frequency circuits.', category: 'antistatic-esd-tapes', features: ['Tin plating prevents oxidation', 'Excellent solderability', 'Provides effective EMI shielding'], uses: ['Corrosion-resistant grounding', 'Shielding in harsh environments', 'PCB manufacturing'], images: ['https://file.garden/aIULwzQ_QkPKQcGw/tin%20copper%20tape.webp'] },
];
